### ISSUE TITLE
Crash after 2 hours

### ISSUE THREAD

**Issue by svigerske** [coin-or/Cbc#140]
Issue created by migration from Trac.

Original creator: Armin

Original creation time: 2013-11-24 21:56:02

Assignee: @tkralphs

Version: 2.8.6

Compiled on MacMini with MacOS10.9.

Cbc0010I After 57200 nodes, 11078 on tree, 1503585.8 best solution, best possible 1363534.2 (7831.46 seconds)
libc++abi.dylib: terminating with uncaught exception of type CoinError
Abort trap: 6

**Comment by svigerske** [comment]
Attachment [model.lp.zip](https://www.coin-or.org/issue-attachments/Cbc/ticket140/model.lp.zip) by Armin created at 2013-11-24 22:00:03

**Comment by svigerske** [comment]
Comment by Armin created at 2013-12-02 07:17:45

Crash also occurs in 2.8.7:

Cbc0010I After 2720800 nodes, 12916 on tree, 1493461.3 best solution, best possible 1363534.2 (132717.53 seconds)
libc++abi.dylib: terminating with uncaught exception of type CoinError
Abort trap: 6

**Comment by svigerske** [comment]
Hard or no longer to reproduce. I've run the current Cbc/master and stopped it after a night:
```
Objective value:                1493392.68000000
Lower bound:                    1393331.476
Gap:                            0.07
Enumerated nodes:               275651
Total iterations:               28652729
Time (CPU seconds):             45561.95
Time (Wallclock seconds):       49484.60
```

**Comment by dshimanshupant** [comment]
Is it resolved?
