### ISSUE TITLE
Version number in releases is 0.0.0

### ISSUE THREAD

**Issue by tomwhoiscontrary** [coin-or/Cbc#192]
I am only slowly getting to grips with COIN-OR, so apologies if this issue is misguided.

In the Linux release tarballs on Bintray, there is a directory build/lib containing lots and lots of shared libraries. These have the usual setup for versioned libraries, with a fully versioned file, and then symbolic links with one and no levels of versioning pointing to the real file. However, the version numbers are all zero:

```
$ ls -1F build/lib/libCbc.so*
build/lib/libCbc.so@
build/lib/libCbc.so.0@
build/lib/libCbc.so.0.0.0*
```

This is true for the 2.9 and 2.9.9 releases.

Is this a mistake?

Does this mean that version numbers embedded in the artifacts in other places are also wrong?

EDIT: Also, in the pkg-config files, we have:

```
prefix=/home/travis/build/coin-or/Cbc/build
```

Which is probably not going to be that useful on users' machines. On the other hand, i'm not sure what i would put here; it depends on where the user installs the package.

**Comment by svigerske** [comment]
I think the svn:externals are set to releases, but the list in the Dependencies file is not. The binaries on bintray have probably used the GitHub-mirror of Cbc as source instead of the original svn repo.
We might want to look into putting releases into the Dependencies file, too, when adapting the release-creation scripts to work on git instead of svn.

**Comment by tkralphs** [comment]
Yes, the Dependencies file needs to contain the releases for the release tagged version of the code. This is one of the things we will address when putting together the scripts that produce releases from the git repos.

**Comment by tomwhoiscontrary** [comment]
I would offer to help, but i had a look at the build system for Cbc and immediately needed a lie down in a darkened room!
