### ISSUE TITLE
Semis section not working as expected.

### ISSUE THREAD

**Issue by richi1986** [coin-or/Cbc#193]
Hi 

I am using version 2.9.9 of cbc in ubuntu 17.10 docker image.
My test.lp file has following content:
**Maximize
 obj: x1 + 2 x2 + 3 x3 + x4
Subject To
 c1: - x1 + x2 + x3 + 10 x4 <= 20
 c2: x1 - 3 x2 + x3 <= 30
 c3: x2 - 3.5 x4 = 0
Bounds
 0 <= x1 <= 40
 2 <= x4 <= 3
General
 x4 
Semis
 x1 x2 x3**
When trying with semis section i get error
"terminate called after throwing an instance of 'CoinError'
Aborted"

on mac i get:
libc++abi.dylib: terminating with uncaught exception of type CoinError
Abort trap: 6

However if I comment out Semis it works fine.
I was hoping that Semis are supported.
Am I doing something wrong?

My command is : `cbc -presolve on -import test.lp solve solu out.txt`

Thanks

**Comment by svigerske** [comment]
Same as #183.
