### ISSUE TITLE
Bintray windows 64bit binary fails to run

### ISSUE THREAD

**Issue by brynpickering** [coin-or/Cbc#195]
On downloading the built binary `Cbc-2.9-x86_64-w64-mingw32.zip` from Bintray (as per your README download link), extracting and trying to run `cbc.exe`, I get an error that ``libbz2-1.dll was not found``. 

I have `bzip2` already installed on my device, which seems to be from where `libbz2` should originate.

Interestingly, an old windows build of Cbc (2.75, found [here](https://www.coin-or.org/download/binary/Cbc/)) does run out of the box.

**Comment by svigerske** [comment]
Closing as no reply from reported for (almost) a year.
