### ISSUE TITLE
Makefile:973: recipe for target 'CbcModel.lo' failed

### ISSUE THREAD

**Issue by sqPoseidon** [coin-or/Cbc#200]
Making all in Cbc
make[1]: Entering directory '/home/qisun/Cbc-releases-2.9.9/build/Cbc'
Making all in src
make[2]: Entering directory '/home/qisun/Cbc-releases-2.9.9/build/Cbc/src'
make  all-am
make[3]: Entering directory '/home/qisun/Cbc-releases-2.9.9/build/Cbc/src'
if /bin/bash ../../libtool --tag=CXX --mode=compile g++ -DHAVE_CONFIG_H -I. -I`echo ../../../Cbc/src` -I../src  -I/usr/include/coin -I/usr/include/coin     -DCOIN_NO_CLP_MESSAGE -DUSE_CBCCONFIG   -O3 -pipe -DNDEBUG -Wparentheses -Wreturn-type -Wcast-qual -Wall -Wpointer-arith -Wwrite-strings -Wconversion -Wno-unknown-pragmas -Wno-long-long   -DCBC_BUILD -MT CbcModel.lo -MD -MP -MF ".deps/CbcModel.Tpo" -c -o CbcModel.lo ../../../Cbc/src/CbcModel.cpp; \
then mv -f ".deps/CbcModel.Tpo" ".deps/CbcModel.Plo"; else rm -f ".deps/CbcModel.Tpo"; exit 1; fi
 g++ -DHAVE_CONFIG_H -I. -I../../../Cbc/src -I../src -I/usr/include/coin -I/usr/include/coin -DCOIN_NO_CLP_MESSAGE -DUSE_CBCCONFIG -O3 -pipe -DNDEBUG -Wparentheses -Wreturn-type -Wcast-qual -Wall -Wpointer-arith -Wwrite-strings -Wconversion -Wno-unknown-pragmas -Wno-long-long -DCBC_BUILD -MT CbcModel.lo -MD -MP -MF .deps/CbcModel.Tpo -c ../../../Cbc/src/CbcModel.cpp  -fPIC -DPIC -o .libs/CbcModel.o
../../../Cbc/src/CbcModel.cpp: In member function 'void CbcModel::branchAndBound(int)':
../../../Cbc/src/CbcModel.cpp:4015:47: error: 'class CglProbing' has no member named 'cliqueModel'
        OsiSolverInterface * temp = generator1.cliqueModel(solver_,2);
                                               ^
../../../Cbc/src/CbcModel.cpp:4039:39: error: no matching function for call to 'CglTreeProbingInfo::analyze(OsiSolverInterface&, int, int)'
   fake = info.analyze(*newSolver, 1,-1);
                                       ^
In file included from /usr/include/coin/CglCutGenerator.hpp:10:0,
                 from ../../../Cbc/src/CbcCutGenerator.hpp:11,
                 from ../../../Cbc/src/CbcModel.cpp:60:
/usr/include/coin/CglTreeInfo.hpp:106:24: note: candidate: OsiSolverInterface* CglTreeProbingInfo::analyze(const OsiSolverInterface&, int)
   OsiSolverInterface * analyze(const OsiSolverInterface & si, int createSolver=0);
                        ^
/usr/include/coin/CglTreeInfo.hpp:106:24: note:   candidate expects 2 arguments, 3 provided
In file included from ../../../Cbc/src/CbcModel.cpp:76:0:
/usr/include/coin/CglKnapsackCover.hpp:235:7: error: 'int CglKnapsackCover::createCliques(OsiSolverInterface&, int, int, bool)' is private
   int createCliques( OsiSolverInterface & si, 
       ^
../../../Cbc/src/CbcModel.cpp:4057:46: error: within this context
       cutGen->createCliques(*fake,2,200,false);
                                              ^
In file included from /usr/include/coin/ClpModel.hpp:23:0,
                 from /usr/include/coin/ClpSimplex.hpp:16,
                 from /usr/include/coin/ClpPresolve.hpp:8,
                 from ../../../Cbc/src/CbcModel.cpp:28:
/usr/include/coin/CoinFinite.hpp: At global scope:
/usr/include/coin/CoinFinite.hpp:20:14: warning: 'COIN_INT_MAX_AS_DOUBLE' defined but not used [-Wunused-variable]
 const double COIN_INT_MAX_AS_DOUBLE = std::numeric_limits<int>::max();
              ^
Makefile:973: recipe for target 'CbcModel.lo' failed
make[3]: *** [CbcModel.lo] Error 1
make[3]: Leaving directory '/home/qisun/Cbc-releases-2.9.9/build/Cbc/src'
Makefile:737: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/qisun/Cbc-releases-2.9.9/build/Cbc/src'
Makefile:586: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/qisun/Cbc-releases-2.9.9/build/Cbc'
Makefile:323: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by svigerske** [comment]
Maybe you somehow got a too old version of Cgl. CglProblem::cliqueModel() was added in 2014.
