### ISSUE TITLE
Cbc ignores some fixed variables

### ISSUE THREAD

**Issue by icze** [coin-or/Cbc#201]
Hallo,

I'm using cbcCInterfaceDll to access Cbc 2.99. While doing some tests I found the problem that sometimes fixed variables are lost. Using the same model with lp_solve or Gurobi works fine.

To reproduce I exported the correct model from Gurobi as mps:
[CbcShowStopper.txt](https://github.com/coin-or/Cbc/files/2577946/CbcShowStopper.txt)

Even importing the file to Cbc and exporting it again shows that e.g. C7 does not hold the fixed value 1 anymore.

Does anybody know a workaround for the problem?
Thanks in advance.

**Comment by svigerske** [comment]
Probably fixed by 117df245764f
