### ISSUE TITLE
Incorrect solution of small IP instance using the C interface and Cbc_setInitialSolution

### ISSUE THREAD

**Issue by GunnarFarneback** [coin-or/Cbc#203]
This problem is similar to #202 but featuring an incorrect result rather than a crash, and no signs of memory corruption.

The original bug report can be found in https://github.com/JuliaOpt/Cbc.jl/issues/94, where an integer maximization problem with 20 variables and 20 constraints yields an optimal solution of 7 without an initial solution and an optimal solution of 6 when an initial solution is provided. I have reduced this to a plain C program [cbc_failure.c.gz](https://github.com/coin-or/Cbc/files/2799948/cbc_failure.c.gz), which gives the incorrect result when run without an argument and the correct result when run with an argument, disabling the call to `Cbc_setInitialSolution`.

**Comment by GunnarFarneback** [comment]
Looks like the attachment was lost in the repository transfer, so I'll paste it here instead.
```
#include "Cbc_C_Interface.h"

int main(int argc, const char **argv) {
    int disable_warmstart = argc > 1;
    void *p = Cbc_newModel();

    CoinBigIndex start[] = {0, 3, 7, 10, 13, 16, 20, 24, 28, 32, 36, 40, 43, 46, 50, 54, 57, 61, 64, 67, 71};

    int index[] = {1, 4, 5, 1, 10, 11, 16, 1, 14, 15, 3, 14, 15, 0, 1, 5, 5, 12, 13, 18, 7, 8, 9, 19, 7, 10, 11, 17, 6, 7, 9, 17, 9, 10, 11, 16, 9, 12, 13, 19, 9, 14, 15, 0, 1, 11, 6, 7, 11, 16, 8, 9, 11, 19, 4, 5, 13, 8, 9, 13, 18, 0, 1, 15, 2, 3, 15, 8, 9, 15, 19};

    double value[] = {1.0, 1.0, -1.0, 1.0, 1.0, -1.0, 1.0, 1.0, 1.0, -1.0, 1.0, 1.0, -1.0, 1.0, -1.0, 1.0, 1.0, 1.0, -1.0, 1.0, 1.0, 1.0, -1.0, 1.0, 1.0, 1.0, -1.0, -1.0, 1.0, -1.0, 1.0, 1.0, 1.0, 1.0, -1.0, 1.0, 1.0, 1.0, -1.0, -1.0, 1.0, 1.0, -1.0, 1.0, -1.0, 1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, 1.0, 1.0, -1.0, 1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, 1.0, -1.0, 1.0, 1.0, -1.0, 1.0, 1.0};

    double col_lb[] = {0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0};

    double col_ub[] = {1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0};

    double obj[] = {1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0};

    double row_lb[] = {0.0, 0.0, 0.0, 1.0, 1.0, -1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0};

    double row_ub[] = {1.0, 0.0, 0.0, 1.0, 1.0, -1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 2.0, 2.0, 2.0, 2.0};

    double initial_solution[] = {1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0};

    Cbc_loadProblem(p, 20, 20, start, index, value, 
                    col_lb, col_ub, obj, row_lb, row_ub);
    Cbc_setObjSense(p, -1.0);
    for (int i = 0; i < 20; i++) {
        Cbc_setInteger(p, i);
    }
    if (!disable_warmstart) {
        Cbc_setInitialSolution(p, initial_solution);
    }
    Cbc_solve(p);
    Cbc_deleteModel(p);
    return 0;
}
```

**Comment by svigerske** [comment]
@jjhforrest commented on this in #202: "Other bug using C interface is to do with the interface not handling maximization totally correctly.  I am not an expert on C interface so would suggest changing model to minimize (worked for me)."

**Comment by h-g-s** [comment]
Hi, @jjhforrest  gave a look here, what is strange is that if I save the model just before optimizing it (writeLp) the objective function is saved properly (obj*-1). Calling CBC for this saved model gives the correct of,    but if I call Cbc_solve (which calls CbcMain0 and CbcMain1) then the objective function is still considered minimization with the unchanged coefficients.

**Comment by svigerske** [comment]
"gave a look" is 8beafa2ae? Maybe this is fixed?

**Comment by jjhforrest** [comment]
Should be fixed
