### ISSUE TITLE
possible memory leak in CbcModel::synchronizeHandlers(int)

### ISSUE THREAD

**Issue by svigerske** [coin-or/Cbc#205]
@davidfischinger reported on Sep 30, 2016 that a memory leak is caused by the line:

     handler_ = handler_->clone();

in `CbcModel::synchronizeHandlers(int)` and suggest to comment out this line (see also https://github.com/davidfischinger/Cbc/commit/7ddaf4b4ece907ce18bdcb6732c277b4dbbb7d27).

**Comment by jjhforrest** [comment]
Should be fixed in trunk
