### ISSUE TITLE
Error Makefile for CygWin/Windows

### ISSUE THREAD

**Issue by cgiraudfreelance** [coin-or/Cbc#209]
With CygWin on Windows, when I compile, I have an error in the makefile file.
When running the configure command, it runs successfully.

Can you help me ?

./configure --prefix=/usr --enable-cbc-parallel --enable-gnu-packages
./make
[result configure and make.txt](https://github.com/coin-or/Cbc/files/2966446/result.configure.and.make.txt)

here is the result file of the configure and make command.

**Comment by cgiraudfreelance** [comment]
here is the makefile error :

Makefile:658: .deps/CoinWarmStartVector.Plo: No such file or directory

$ make
Making all in ThirdParty/ASL
make[1] : on entre dans le répertoire « /cygdrive/c/new2/ThirdParty/ASL »
make[1]: rien à faire pour « all ».
make[1] : on quitte le répertoire « /cygdrive/c/new2/ThirdParty/ASL »
Making all in Data/Sample
make[1] : on entre dans le répertoire « /cygdrive/c/new2/Data/Sample »
make[1]: rien à faire pour « all ».
make[1] : on quitte le répertoire « /cygdrive/c/new2/Data/Sample »
Making all in Data/miplib3
make[1] : on entre dans le répertoire « /cygdrive/c/new2/Data/miplib3 »
make[1]: rien à faire pour « all ».
make[1] : on quitte le répertoire « /cygdrive/c/new2/Data/miplib3 »
Making all in CoinUtils
make[1] : on entre dans le répertoire « /cygdrive/c/new2/CoinUtils »
Making all in src
make[2] : on entre dans le répertoire « /cygdrive/c/new2/CoinUtils/src »
Makefile:658: .deps/CoinWarmStartVector.Plo: No such file or directory
make[2]: *** Aucune règle pour fabriquer la cible « .deps/CoinWarmStartVector.Plo ». Arrêt.
make[2] : on quitte le répertoire « /cygdrive/c/new2/CoinUtils/src »
make[1]: *** [Makefile:436: all-recursive] Error 1
make[1] : on quitte le répertoire « /cygdrive/c/new2/CoinUtils »
make: *** [Makefile:323: all-recursive] Error 1

**Comment by svigerske** [comment]
It seems that there was already a failing run of `make` in the same directory and we do not see this in the log. Try removing everything and restart from scratch and store the full log.

**Comment by cgiraudfreelance** [comment]
Here is the trace file of the 2 commands executed.

As requested, I created a new folder and then:
1. I downloaded version 2.9 on SVN with the Tortoise SVN application on Windows.
2. I ran the command ./configure --prefix = / usr --enable-cbc-parallel --enable-gnu-packages
./make
3. I executed the command
./make

I always have the same mistake:

Making all in src
make [2]: we enter the directory "/cygdrive/c/new3/2.9/CoinUtils/src"
Makefile: 658: .deps / CoinWarmStartVector.Plo: No such file or directory
make [2]: *** No rules for making the target ".deps / CoinWarmStartVector.Plo". Stop.
make [2]: we leave the directory "/cygdrive/c/new3/2.9/CoinUtils/src"
make [1]: *** [Makefile: 436: all-recursive] Error 1
make [1]: we leave the directory "/cygdrive/c/new3/2.9/CoinUtils"
make: *** [Makefile: 323: all-recursive] Error 1


[log configure and make.txt](https://github.com/coin-or/Cbc/files/2968748/log.configure.and.make.txt)

**Comment by svigerske** [comment]
Hmm, maybe you can also post `/cygdrive/c/new3/2.9/CoinUtils/src/Makefile`

**Comment by cgiraudfreelance** [comment]
I found the origin of the problem:
- When I download via tortoisesvn, it does not work.
- When I download via svn under the cygwin terminal, it works.

**Comment by tkralphs** [comment]
This is probably due to somehow getting a mix of line endings. The Windows client may change some line endings.
