### ISSUE TITLE
Optimization LP Relaxation

### ISSUE THREAD

**Issue by cgiraudfreelance** [coin-or/Cbc#210]
Hello,
[Etape2.zip](https://github.com/coin-or/Cbc/files/3002099/Etape2.zip)

I have a particularly long treatment for the LP Relaxation part.
Here is my file to process.
What are my methods to optimize this treatment?

**Comment by h-g-s** [comment]
Took a look at your MIP, it seems that pre-processing takes some time, but it is clearly worth it. After that it spend some time generating cuts (also worth it).  It also spends some time in the heuristic feasibility pump. If you could provide the solve an initial feasible solution - by writing some simple problem dependent heuristic you could perhaps deactivate this step (-passf=0).
