### ISSUE TITLE
Perfomance increase of CBC 2.10.3 vs 2.9.9?

### ISSUE THREAD

**Issue by rlloretb** [coin-or/Cbc#212]
It seems that 2.10.X has included new features targeting performance increase.
Would it be possible/ has it been done to run a benchmark on 2.10.X vs 2.9.9?

**Comment by h-g-s** [comment]
Almost all changes since 2.9 were fixes. Some small performance gain may happen, but it is probably marginal. The next release will probably  contain new cut generators and pre-processing routines based on conflict graphs and some significant performance improved may be achieved.

**Comment by rlloretb** [comment]
Which is the performance increase for 2.10.3?

**Comment by svigerske** [comment]
2

**Comment by rlloretb** [comment]
Any news about performance increase?
