### ISSUE TITLE
Bintray version if 2.10.0 while the latest version is 2.10.1.

### ISSUE THREAD

**Issue by Moisan** [coin-or/Cbc#216]
Would it be possible to update the bintray binaries to the latest version?

**Comment by tkralphs** [comment]
What platform? I noticed that 2.10.1 had been missed during a period when the Travis jobs were not being launched properly. I don't see an easy way to trigger a Travis build of a particular tag, though. There are binaries for 2.10, which should be almost identical to 2.10.1.

**Comment by Moisan** [comment]
I'm looking at binaries for Linux in particular.

**Comment by svigerske** [comment]
For 2.10.2, the [log of the travis build for Linux](https://api.travis-ci.org/v3/job/522923375/log.txt) has
```
[0K$ curl -T $TGZ_FILE -utkralphs:$BINTRAY_API -H "X-Bintray-Publish:1" -H "X-Bintray-Override:1" https://api.bintray.com/content/coin-or/download/$PROJECT/$VERSION/$TGZ_FILE
{"message":"This resource requires authentication"}travis_time:end:1869863a:start=1555913628030445089,finish=1555913628442069013,duration=411623924
```
I don't see how the BINTRAY_API variable is set, but also don't know how Travis configuration works.

**Comment by tkralphs** [comment]
Ugh, OK, I'm not entirely sure, but I think this may be because we moved everything to a new Github repo and now all the secure variables need to be re-encrypted... this is a manual process, will check it as soon as I can.

**Comment by tkralphs** [comment]
OK, I fixed the issue with the bintray authentication and now binaries are being uploaded again Unfortunately, there is still no way that I know of to trigger a re-build of a tag, so we'll need to make release 2.10.3 to get release binaries. Before that, the fixes need to merged over to `stable/2.10`.

In the meantime, though I was trying to see if I could make static binaries (these were requested by someone else) and I can't seem to make the Linux binaries fully static, even with the usual incantations. @svigerske do you know how to do this?

**Comment by svigerske** [comment]
If you lucky, then `--disable-shared LDFLAGS=-static` could work. But this requires that you have static version of all the standard libraries (libc, libstdc++, libgfortran) available.

On my system, I don't seem to have a static version of libgfortran, and I didn't look whether I could install one. So I only used `configure -C --disable-shared LDFLAGS="-static-libgcc -static-libstdc++"`. With that, I have plenty of shared library dependencies:
```
	linux-vdso.so.1 (0x00007ffe9a1c4000)
	libbz2.so.1.0 => /usr/lib/libbz2.so.1.0 (0x00007fc1256b3000)
	libz.so.1 => /usr/lib/libz.so.1 (0x00007fc12549c000)
	liblapack.so.3 => /usr/lib/liblapack.so.3 (0x00007fc124bba000)
	libopenblas.so.3 => /usr/lib/libopenblas.so.3 (0x00007fc12398b000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007fc123986000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007fc123840000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007fc123679000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007fc125e24000)
	libgfortran.so.5 => /usr/lib/libgfortran.so.5 (0x00007fc1233fd000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007fc1233e3000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007fc1233c2000)
	libgomp.so.1 => /usr/lib/libgomp.so.1 (0x00007fc123392000)
	libquadmath.so.0 => /usr/lib/../lib/libquadmath.so.0 (0x00007fc12334d000)
```
libz and libbz2 I could get rid off with `--disable-zlib` and `--disable-bzlib`. lapack and openblas I could get rid off by forcing to use the ThirdParty versions or installing static versions of these libs.
libdl, libm, libc, libpthread one can assume to be present on any Linux system.

**Comment by tkralphs** [comment]
Looks like changes were merged so I'm closing this. Look for the next release. In the meantime, binaries for current commit on master and stable/2.10 are on bintray.
