### ISSUE TITLE
No release 1.2.11 of Data-Sample

### ISSUE THREAD

**Issue by tkralphs** [coin-or/Cbc#220]
In the latest release of Cbc, the Dependencies file refers to release 1.2.11 of [Data-Sample](https://github.com/coin-or-tools/Data-Sample), which doesn't exist. @svigerske perhaps you didn't push the release of committed it to the SVN repo instead of git?

**Comment by tkralphs** [comment]
OK, I guess you committed to SVN. I just mirrored SVN again, so the releases are there, but I think we can switch to git for the Data projects, right?

**Comment by svigerske** [comment]
I made the 1.12.11 release on the svn last November when we were starting to get out a releases of the Optimization Suite, incl. its dependencies (which then got stuck and then resumed in February). As most projects were still living on svn, they had dependencies on Data/Sample from svn, so the release had to be made there.

It was probably too early to disable the mirroring for Data-projects while there are still so many projects on svn depend on it.
We can leave the mirroring off and hope that there will be no more changes to the projects while they are still used as svn-dependencies of others. But if there are, you would have to manually rerun your svn-to-git-repo migration script again.

If you have disabled mirroring for ThirdParty-projects, too, then it might be good to have a look whether the versions on GitHub are still uptodate.
