### ISSUE TITLE
Segmentation fault trying to solve a cloned model in C API

### ISSUE THREAD

**Issue by AndreaB2604** [coin-or/Cbc#225]
Using the C API: when I try to solve a model, using Cbc_solve(), which has been cloned, using Cbc_clone(), the program ends with a segmentation fault in the Cbc_solve() function; but if I try to call the solve function with the original model there is no error.
I hope this information will be helpful.
Thanks

**Comment by h-g-s** [comment]
I'm probably not cloning some buffered information. I'll check it.

**Comment by h-g-s** [comment]
Just pushed new code,  could you please check?

**Comment by AndreaB2604** [comment]
Great job, I checked and now the clone function works, but I think there is a another problem with the read_Lp and read_Mps functions because if I write a model and I read it, it ends with segmentation fault. The model written by the write_Lp is correct, so I think the problem is in the read. For the write_Mps I think it is correct but I'm not so sure, because I'm not used to using .mps files, sorry.
Thank you for your work.

**Comment by AndreaB2604** [comment]
I realize I can solve a model written in files using the command line. I tried to solve a mps file and the model is solved correctly, so the problem is in the read functions. I think I found also a minor bug in the Cbc_isProvenInfeasible() and in the Cbc_isProvenOptimal() because if I try to solve a model the functions work correctly, but if I add new constraints that make the problem infeasible, and solve again the problem, the log printed are right, while the functions return the same values as before and they should be swapped

**Comment by h-g-s** [comment]
I'll close this issue, could you create other issues with the respective problems ?
