### ISSUE TITLE
Windows binaries for DEBUG configurations

### ISSUE THREAD

**Issue by gioid** [coin-or/Cbc#232]
I downloaded the binaries (Cbc-2.10.0-win32-msvc14.zip) for the version 2.10.0 from here:
https://bintray.com/coin-or/download/Cbc/2.10.0

When I include the .h and the .libs in my project on VisualStudio 2017 (using Platform Toolset Visual Studio 2015 v140), I can build the solution for Release configuration, but if I try to build with Debug configuration, I obtain lot of linker errors like the following:

```
1>libCbc.lib(CbcModel.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in CbcLinearProgramming.obj
1>libCbc.lib(CbcModel.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MDd_DynamicDebug' in CbcLinearProgramming.obj
...
```

I think this is because the binaries that I downloaded have been built for Release configuration. I am wondering if I can find also the full package for the Debug configuration.

**Comment by tkralphs** [comment]
I guess you are right. I have so far not provided binaries built in Debug configuration, since that would double the build time and this is the first request I've had. The provided Visual Studio solution files should be up to date and should allow you to build your own binaries without much difficulty. Have you tried those?

**Comment by gioid** [comment]
Thanks for you fast feedback. I tried and I successfully built the Cbc .libs, both in Debug and in Release, both for "Platform Toolset" v140 and v141.

I asked to you because it would be really convenient to find the artifacts ready for the download, for each released version. I don't know if you can adapt the builds definitions differently between the "master/develop" branch and the official releases: if you can, I think that just the Release artifacts are more than enough for experiments and tests. Instead, for an "official/released" version I think that is more important the availability of debug artifacts, to allow easy integration of your versions in broader workflows.

Anyway, I really appreciate both the quality/results of the library that you developed (and you are still developing) and the help/support that you provide to your users base.

**Comment by tkralphs** [comment]
I think it should not be difficult to build binaries in Debug mode for releases only and this makes sense. I will look into it. Thanks!

**Comment by tkralphs** [comment]
OK, now there are binaries built from master compiled with /MT, /MD, /MTd, /MDd with Visual Studio Versions 2015, 2017, and 2019. I guess that should cover it for now! At some point soon, this setup will also move to stable/2.10, which may be more useful. I'm going to close this for now.

**Comment by gioid** [comment]
Many thanks.
