### ISSUE TITLE
CBC crashing when writing the solution file

### ISSUE THREAD

**Issue by vignesh1987** [coin-or/Cbc#233]
Hi,

I am using CBC to solve a cost minimization model. CBC pre-solves the model, and when it has to start the main optimization routine, it crashes (it shows an optimal value but does not write the solution). The size of the LP file (that is being optimized) is 7 GB. The surprising thing is that I do not reach any upper limits concerning CPU or RAM usage. I tried it on different computers (RAM32GB-256GB) and the same result. Can someone help me with this?

I also tried running with CPLEX, and it solves the model (with the same Optimal value) and writes the solution. I am surprised why CBC crashes and does not write results. Is there a limit/cut off on how much time CBC can take to write solution files? if it exists, can this limit be extended?

CBC version: 2.7.5
OS: Windows 10

**Comment by svigerske** [comment]
There are no limits on time to write a solution.

Cbc 2.7.5 is very old. Try first whether this works better with a current version (2.10.x).

**Comment by willu47** [comment]
I have also had this same problem when trying to write a large (~5GB) solution file, using Mac OSX and the latest version of CBC installed via Homebrew. CBC crashes with a segmentation fault 11 when using the argument `-solu` or `-saveS` to write the solution.

**Comment by h-g-s** [comment]
Could you please provide the instance where the problem happens ?

-- 
=============================================================
Haroldo Gambini Santos
Computing Department
Universidade Federal de Ouro Preto - UFOP
email: haroldo@ufop.edu.br
        Haroldo.GambiniSantos@cs.kuleuven.be
home/research page: www.decom.ufop.br/haroldo


It has long been an axiom of mine that the little things are infinitely
the most important.
-- Sir Arthur Conan Doyle, "A Case of Identity"

**Comment by willu47** [comment]
Hi @h-g-s - Sure, I run `cbc temba.lp solve -solu output_data/solutionfile.txt` from the command line, where `temba.lp` is a large file in LP format.  The solve, which takes several hours, finishes successfully with an optimal solution (confirmed using CPLEX and Gurobi solvers to compare objective functions on stdout).  Finally, CBC crashes as it is trying to write to solution file with an out of memory error (segmentation fault).  I will check if I can share the .LP file publicly to see if you can recreate this.

**Comment by willu47** [comment]
@h-g-s - I've sent you an e-mail with a link to the LP file.

**Comment by h-g-s** [comment]
Great. I'll try to reproduce the bug.

-- 
=============================================================
Haroldo Gambini Santos
Computing Department
Universidade Federal de Ouro Preto - UFOP
email: haroldo@ufop.edu.br
        Haroldo.GambiniSantos@cs.kuleuven.be
home/research page: www.decom.ufop.br/haroldo


It has long been an axiom of mine that the little things are infinitely
the most important.
-- Sir Arthur Conan Doyle, "A Case of Identity"

**Comment by willu47** [comment]
Awesome, thanks so much!

**Comment by h-g-s** [comment]
Tested here, with a time limit of 7200 seconds, a solution (not optimal) 
was generated and saved.

Which CBC version you are using ? There are some recent fixes in trunk. 
Could you try it ?


-- 
=============================================================
Haroldo Gambini Santos
Computing Department
Universidade Federal de Ouro Preto - UFOP
email: haroldo@ufop.edu.br
        Haroldo.GambiniSantos@cs.kuleuven.be
home/research page: www.decom.ufop.br/haroldo


It has long been an axiom of mine that the little things are infinitely
the most important.
-- Sir Arthur Conan Doyle, "A Case of Identity"

**Comment by willu47** [comment]
> Which CBC version you are using ? There are some recent fixes in trunk. Could you try it ?

I'm running on Mac OSX 10.14.5 with CBC installed via Homebrew.

```
$ cbc output_data/temba.lp solve -solu output_data/solutionfile.txt -sec 600
Welcome to the CBC MILP Solver 
Version: 2.10.2 
Build Date: Jul 19 2019 

command line - cbc output_data/temba.lp solve -solu output_data/solutionfile.txt -sec 600 (default strategy 1)
...
```

**Comment by willu47** [comment]
So, after running CBC using the above command, I received the following error:
```bash
$ cbc output_data/temba.lp solve -solu output_data/solutionfile.txt -sec 600
Welcome to the CBC MILP Solver 
Version: 2.10.2 
Build Date: Jul 19 2019 

command line - cbc output_data/temba.lp solve -solu output_data/solutionfile.txt -sec 600 (default strategy 1)
Presolve 1109563 (-6069771) rows, 1092309 (-4459755) columns and 20602177 (-91678892) elements
Perturbing problem by 0.001% of 6.6728285e-10 - largest nonzero change 9.9999897e-08 ( 1.3511362e+09%) - largest zero change 9.9999105e-08
0  Obj 1.7246471e+10 Primal inf 15186888 (42693) Dual inf 268857.77 (18384)
1000  Obj 9.7256711e+09 Primal inf 1.4854617e+11 (64505)
2000  Obj 1.1084906e+10 Primal inf 1.0090883e+11 (62699)
3000  Obj 1.2340986e+10 Primal inf 9.0616562e+10 (62689)
4000  Obj 1.2950106e+10 Primal inf 8.7854669e+10 (63244)
5000  Obj 1.3636218e+10 Primal inf 8.8710559e+10 (63743)
6000  Obj 1.4136895e+10 Primal inf 8.2090386e+10 (64214)
<snip>
1270343  Obj 1.732353e+10
Optimal - objective value 1.732353e+10
After Postsolve, objective 1.732353e+10, infeasibilities - dual 0.0024139755 (7519), primal 0.0043161333 (18)
Presolved model was optimal, full model needs cleaning up
Segmentation fault: 11
```

My `-sec` argument didn't seem to work.

**Comment by tkralphs** [comment]
@willu47 I guess that to have an effect, `-sec 600` would need to come before `solve` on the command line. 

@h-g-s If necessary, I can try to run on OS X with Cbc installed from Homebrew to replicate. I'll need the link to the instance, though.

**Comment by willu47** [comment]
If I `Ctrl + C` the presolve, then I can successfully write the solution file (albeit with an non-optimal solution)
```
502780  Obj 1.7291229e+10 Primal inf 19974189 (128857)
503780  Obj 1.7291229e+10 Primal inf 21984235 (130325)
504780  Obj 1.729123e+10 Primal inf 97965661 (130515)
^CStopped - objective value 1.729123e+10
Presolved problem not optimal, resolve after postsolve
After Postsolve, objective 1.729123e+10, infeasibilities - dual 5117373.8 (40114), primal 9.4502694e+08 (132998)
Stopped objective 1.729123e+10 - 505058 iterations time 559.142, Presolve 21.54

Result - Stopped on node limit

Enumerated nodes:           0
Total iterations:           0
Time (CPU seconds):         672.98
Time (Wallclock Seconds):   755.14

seconds was changed from 1e+100 to 10
Total time (CPU seconds):       675.76   (Wallclock seconds):       758.51
```

**Comment by willu47** [comment]
If I `Ctrl + C` the presolve, then I can successfully write the solution file (albeit with an non-optimal solution)
```
502780  Obj 1.7291229e+10 Primal inf 19974189 (128857)
503780  Obj 1.7291229e+10 Primal inf 21984235 (130325)
504780  Obj 1.729123e+10 Primal inf 97965661 (130515)
^CStopped - objective value 1.729123e+10
Presolved problem not optimal, resolve after postsolve
After Postsolve, objective 1.729123e+10, infeasibilities - dual 5117373.8 (40114), primal 9.4502694e+08 (132998)
Stopped objective 1.729123e+10 - 505058 iterations time 559.142, Presolve 21.54

Result - Stopped on node limit

Enumerated nodes:           0
Total iterations:           0
Time (CPU seconds):         672.98
Time (Wallclock Seconds):   755.14

seconds was changed from 1e+100 to 10
Total time (CPU seconds):       675.76   (Wallclock seconds):       758.51
```

**Comment by willu47** [comment]
I ran this from the command line tool, and I now believe that the segmentation fault is caused by the end of solve stage, not the writing of the solution file.  Could you try solving the LP I shared @h-g-s to see if you can reproduce this issue?

**Comment by h-g-s** [comment]
Hi,

I tried to solve your problem, but after several hours no solution was 
found. Did you use some specific additional settings to solve it ?  It 
seems that your problem is too hard for CBC now...



-- 
=============================================================
Haroldo Gambini Santos
Computing Department
Universidade Federal de Ouro Preto - UFOP
email: haroldo@ufop.edu.br
        Haroldo.GambiniSantos@cs.kuleuven.be
home/research page: www.decom.ufop.br/haroldo


It has long been an axiom of mine that the little things are infinitely
the most important.
-- Sir Arthur Conan Doyle, "A Case of Identity"

**Comment by willu47** [comment]
@h-g-s - no special settings - we generally wait for a number of hours before finding a solution after 1,270,343 iterations...  Having said that, I've never seen the solution because of this error!

@tkralphs - I've sent you a link to the zipped .lp file to see if you can try to replicate the error I'm getting.

**Comment by tkralphs** [comment]
@willu47 Can you send the file using [this](https://filesender.lehigh.edu/) to save me having to sign up for Box just to retrieve the file? Thanks!

**Comment by willu47** [comment]
> @willu47 Can yous end the file using [this}(https://filesender.lehigh.edu/) to save me having to sign up for Box just to retrieve the file? Thanks!

Hi @tkralphs - yep, I've now sent you the file using filesender. Thanks in advance for having a look!

**Comment by tkralphs** [comment]
Finally got back to this. With
```
cbc temba.lp -sec 600 solve -solu solutionfile.txt
```
output was
```
command line - cbc temba.lp -sec 600 solve -solu solutionfile.txt (default strategy 1)
seconds was changed from 1e+100 to 600
Presolve 1109563 (-6069771) rows, 1092309 (-4459755) columns and 20602177 (-91678892) elements
Perturbing problem by 0.001% of 6.6728285e-10 - largest nonzero change 9.9999897e-08 ( 1.3511362e+09%) - largest zero change 9.9999105e-08
0  Obj 1.7246471e+10 Primal inf 15186888 (42693) Dual inf 268857.77 (18384)
1000  Obj 9.7256711e+09 Primal inf 1.4854617e+11 (64505)
<snip>
Stopped - objective value 1.7288538e+10
Presolved problem not optimal, resolve after postsolve
After Postsolve, objective 1.7288538e+10, infeasibilities - dual 5117501.1 (39263), primal 2.6417576e+08 (128997)
Stopped objective 1.728853821e+10 - 464856 iterations time 604.992, Presolve 38.77

Result - Stopped on time limit

Enumerated nodes:           0
Total iterations:           0
Time (CPU seconds):         785.96
Time (Wallclock Seconds):   3659.53

Total time (CPU seconds):       790.08   (Wallclock seconds):       3672.52
```
The solution file was created (but reports that the process was stopped on iterations). It seems to be stopping on CPU time, not wall time, and I guess that pre-solve time is not included in the CPU total, but is included in the wall clock total (there is a big discrepancy there), we should check that. I'm trying now with no time limit.

**Comment by willu47** [comment]
Great - looks like you've replicated the successful writing of an empty solution file when running with a time limit (strange that the wallclock is so different).  Hopefully you should now see the bug manifest after the feasible solution is found (`Optimal - objective value 1.732353e+10`).

**Comment by tkralphs** [comment]
Actually, the solution file wasn't empty, I did get a solution with time limit.

**Comment by tkralphs** [comment]
I still haven't managed to replicate this bug while running in a debugger (debugging on OS X is painful). With `gcc` on Linux, I got to
```
Optimal - objective value 1.732353e+10
After Postsolve, objective 1.732353e+10, infeasibilities - dual 0.0024139755 (7519), primal 0.0043161333 (18)
Presolved model was optimal, full model needs cleaning up
```
and then let it run for another day or two. It never crashed, but also didn't finish. In fact, it became clear from the output that it probably wouldn't finish for at least a few more days, if not more, so I killed it.

The same thing happened with `gcc` on OS X. With `clang` on OS X, I did see the crash, but some weird stuff was going on when running `gdb` with `clang`, which I still haven't worked out. 

I guess this problem is pretty poorly scaled, which is why it needs cleanup, but it's just too big to look at and see how to improve it. If you have a smaller version or the actual model that generated it, we could try to help with a better way of formulating it. I'll make one more try at debugging, but it seems clear that getting past this bug is not going to solve your problem.

If you want to try yourself, you can install `gcc` with homebrew on OS X and then build with `CC=gcc CXX=g++`.

**Comment by willu47** [comment]
Hi @tkralphs - thanks so much for taking a look at this and I'm sorry it wasn't the easiest problem to work with! I have managed to successfully solve it using commercial solvers, but yes, the problem is poorly scaled. The model is generated using [OSeMOSYS](http://github.com/OSeMOSYS/OSeMOSYS), so we do have many smaller versions of the problem. But perhaps this is something we can dig into further in the future.

**Comment by tkralphs** [comment]
OK, I'll close the issue for now until we can get something easier to replicate.

**Comment by pickardj79** [comment]
Hi @tkralphs - I'm experiencing this same problem with a ~900MB datafile. I'm not sure the best way to get help or to report it. I realize this issue it closed, but it appears to be most similar to my issue. Let me know if there's a preferred way for me to report this.

Cbc appears to solve the model in a few minutes after a mesage "Presolved model was optimal, full model needs cleaning up" and then gives a seg fault. However, with a slight change to one of the input constraints cbc finds an optimal solution, though that constraint isn't utilized (it's an upper constraint and the solution does not appear to hit against it). I'm running on AWS EC2 m5.4xlarge instance, Amazon Linux AMI (Fedora)

Output from Seg Fault run:
```
>> /mnt/workspace/conda-envs/ec2/bin/cbc -sec 28800 -timeMode elapsed -printingOptions all -import /tmp/tmpf225s0nr.pyomo.lp -stat=1 -solve -solu /tmp/tmpf225s0nr
.pyomo.lp
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Sep 10 2019

command line - /mnt/workspace/conda-envs/ec2/bin/cbc -sec 28800 -timeMode elapsed -printingOptions all -import /tmp/tmpf225s0nr.pyomo.lp -stat=1 -solve -solu /tmp/tmpf225s0nr.pyomo.lp (default strategy 1)
seconds was changed from 1e+100 to 28800
Option for timeMode changed from cpu to elapsed
Option for printingOptions changed from normal to all
Presolve 114 (-4518851) rows, 4515831 (-3020) columns and 42303695 (-4538842) elements
Statistics for presolved model


Problem has 114 rows, 4515831 columns (4466760 with objective) and 42303695 elements
Column breakdown:
0 of type 0.0->inf, 3419130 of type 0.0->up, 0 of type lo->inf,
0 of type lo->up, 0 of type free, 0 of type fixed,
0 of type -inf->0.0, 0 of type -inf->up, 1096701 of type 0.0->1.0
Row breakdown:
0 of type E 0.0, 0 of type E 1.0, 0 of type E -1.0,
0 of type E other, 0 of type G 0.0, 0 of type G 1.0,
61 of type G other, 0 of type L 0.0, 0 of type L 1.0,
53 of type L other, 0 of type Range 0.0->1.0, 0 of type Range other,
0 of type Free
Presolve 114 (-4518851) rows, 4515831 (-3020) columns and 42303695 (-4538842) elements
Perturbing problem by 0.001% of 0.91 - largest nonzero change 0.00041622768 ( 13.161606%) - largest zero change 0.00041622307
0  Obj 0 Primal inf 1.1756021e+09 (61) Dual inf 1415977.7 (4466760)
34  Obj -1.0142806e+08 Primal inf 17401180 (38)
75  Obj -1.0131512e+08 Primal inf 15805172 (45)
125  Obj -1.0116604e+08 Primal inf 16881608 (52)
174  Obj -1.0110964e+08 Primal inf 8136352.7 (51)
217  Obj -1.0109178e+08 Primal inf 9308945 (50)
260  Obj -1.0108505e+08 Primal inf 4882567.4 (51)
308  Obj -1.0106719e+08 Primal inf 2458565.9 (50)
373  Obj -1.0105724e+08 Primal inf 342682.81 (42)
446  Obj -1.01057e+08 Primal inf 12404.549 (18)
507  Obj -1.01057e+08 Primal inf 332.64662 (6)
516  Obj -1.01057e+08
516  Obj -1.0120169e+08 Dual inf 0.0051493265 (13)
529  Obj -1.0120169e+08
Optimal - objective value -1.0120169e+08
After Postsolve, objective -1.0120169e+08, infeasibilities - dual 0 (0), primal 0.0012522036 (3)
Presolved model was optimal, full model needs cleaning up
Segmentation fault
>>
```

Output from successful run
```
>> /mnt/workspace/conda-envs/ec2/bin/cbc -sec 28800 -timeMode elapsed -printingOptions all -import /tmp/tmp2laojfgx.pyomo.lp -stat=1 -solve -solu /tmp/tmp2laojfgx.
pyomo.soln
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Sep 10 2019

command line - /mnt/workspace/conda-envs/ec2/bin/cbc -sec 28800 -timeMode elapsed -printingOptions all -import /tmp/tmp2laojfgx.pyomo.lp -stat=1 -solve -solu /tmp/tmp2laojfgx.pyomo.soln (default strategy 1)
seconds was changed from 1e+100 to 28800
Option for timeMode changed from cpu to elapsed
Option for printingOptions changed from normal to all
Presolve 114 (-4518851) rows, 4515599 (-3252) columns and 42302288 (-4540249) elements
Statistics for presolved model


Problem has 114 rows, 4515599 columns (4466558 with objective) and 42302288 elements
Column breakdown:
0 of type 0.0->inf, 3419028 of type 0.0->up, 0 of type lo->inf,
0 of type lo->up, 0 of type free, 0 of type fixed,
0 of type -inf->0.0, 0 of type -inf->up, 1096571 of type 0.0->1.0
Row breakdown:
0 of type E 0.0, 0 of type E 1.0, 0 of type E -1.0,
0 of type E other, 0 of type G 0.0, 0 of type G 1.0,
61 of type G other, 0 of type L 0.0, 0 of type L 1.0,
53 of type L other, 0 of type Range 0.0->1.0, 0 of type Range other,
0 of type Free
Presolve 114 (-4518851) rows, 4515599 (-3252) columns and 42302288 (-4540249) elements
Perturbing problem by 0.001% of 0.91 - largest nonzero change 0.00041622776 ( 13.162179%) - largest zero change 0.00041622307
0  Obj 0 Primal inf 1.1756021e+09 (61) Dual inf 1415916.1 (4466558)
31  Obj -1.02499e+08 Primal inf 1.1815373e+08 (56)
67  Obj -1.0233024e+08 Primal inf 1.0948092e+08 (54)
114  Obj -1.0230013e+08 Primal inf 1.1404861e+08 (53)
152  Obj -1.0222245e+08 Primal inf 67454629 (55)
197  Obj -1.0215543e+08 Primal inf 1.1499724e+08 (54)
243  Obj -1.0215531e+08 Primal inf 84337363 (55)
287  Obj -1.0212789e+08 Primal inf 1.094528e+08 (55)
332  Obj -1.0212773e+08 Primal inf 96248291 (55)
377  Obj -1.0207956e+08 Primal inf 53206764 (55)
422  Obj -1.0189339e+08 Primal inf 40304273 (55)
467  Obj -1.0188284e+08 Primal inf 68913620 (55)
519  Obj -1.0172244e+08 Primal inf 44456894 (55)
567  Obj -1.0153877e+08 Primal inf 83252149 (55)
616  Obj -1.0153776e+08 Primal inf 61117559 (54)
660  Obj -1.015377e+08 Primal inf 85993674 (54)
707  Obj -1.0153768e+08 Primal inf 64886788 (53)
749  Obj -1.0153655e+08 Primal inf 29809121 (53)
790  Obj -1.0153653e+08 Primal inf 55767435 (55)
835  Obj -1.0152636e+08 Primal inf 14805914 (52)
883  Obj -1.0147879e+08 Primal inf 11803908 (51)
941  Obj -1.0142616e+08 Primal inf 6857433 (51)
1003  Obj -1.0141373e+08 Primal inf 4390793 (49)
1056  Obj -1.0140819e+08 Primal inf 3030464.2 (46)
1121  Obj -1.0140161e+08 Primal inf 1177708.3 (42)
1180  Obj -1.0139936e+08 Primal inf 679203.94 (42)
1237  Obj -1.013991e+08 Primal inf 398480.31 (40)
1287  Obj -1.0139909e+08 Primal inf 420678.87 (40)
1342  Obj -1.0139903e+08 Primal inf 79099.01 (35)
1419  Obj -1.0139903e+08 Primal inf 586.91929 (12)
1447  Obj -1.0139903e+08
Optimal - objective value -1.0154868e+08
After Postsolve, objective -1.0154868e+08, infeasibilities - dual 0 (0), primal 0 (0)
Optimal objective -101548679.1 - 1447 iterations time 161.082, Presolve 39.87
Total time (CPU seconds):       272.51   (Wallclock seconds):       286.01
>>
```
