### ISSUE TITLE
Perfomance increase of CBC 2.10.3 vs 2.9.9?

### ISSUE THREAD

**Issue by rlloretb** [coin-or/Cbc#234]
Any news of performance increase of CBC 2.10.3 vs 2.9.9?

**Comment by svigerske** [comment]
Seems that noone here really looks into doing such benchmarks. Doing them right is a lot of work and the chance that any numbers would be applicable to the instances you want to solve is small, too.
You're welcome to run a benchmark on instances interesting to you and do some comparison.
