### ISSUE TITLE
slowly New functions in the C interface Cbc_addRow

### ISSUE THREAD

**Issue by zhengdi1992** [coin-or/Cbc#237]
i have build a model  var 114213 and constrains 600000, 
`Cbc_addCol()` build fast but `Cbc_addRow()` build slowly and slowly..
i find that
```
/** Adds a new row */
COINLIBAPI void COINLINKAGE
Cbc_addRow(Cbc_Model *model, const char *name, int nz,
  const int *cols, const double *coefs, char sense, double rhs)
{
  Cbc_flush(model);
  OsiSolverInterface *solver = model->model_->solver();
  double rowLB = -DBL_MAX, rowUB = DBL_MAX;
  switch (toupper(sense)) {
  case '=':
    rowLB = rowUB = rhs;
    break;
  case 'E':
    rowLB = rowUB = rhs;
    break;
  case '<':
    rowUB = rhs;
    break;
  case 'L':
    rowUB = rhs;
    break;
  case '>':
    rowLB = rhs;
    break;
  case 'G':
    rowLB = rhs;
    break;
  default:
    fprintf(stderr, "unknow row sense %c.", toupper(sense));
    abort();
  }
  solver->addRow(nz, cols, coefs, rowLB, rowUB);
  solver->setRowName(solver->getNumRows() - 1, std::string(name));
}
```
the ` Cbc_flush(model);` is necessary?  i thought here will cost a lot time .

**Comment by h-g-s** [comment]
Hi,

Cbc_flush is only costly when you alternate between adding columns and 
rows.

For example:

Cbc_addCol
Cbc_addCol
Cbc_addCol
Cbc_addRow
Cbc_addRow
Cbc_addRow

should be faster than

Cbc_addCol
Cbc_addRow
Cbc_addCol
Cbc_addRow
Cbc_addCol
Cbc_addRow


In the first case only two flushes would be performed. In the second every 
call (except the first one) would trigger a flush.

Cheers,

Haroldo

-- 
=============================================================
Haroldo Gambini Santos
Computing Department
Universidade Federal de Ouro Preto - UFOP
email: haroldo@ufop.edu.br
        Haroldo.GambiniSantos@cs.kuleuven.be
home/research page: www.decom.ufop.br/haroldo


It has long been an axiom of mine that the little things are infinitely
the most important.
-- Sir Arthur Conan Doyle, "A Case of Identity"

**Comment by zhengdi1992** [comment]
i find it also locate in the first of `Cbc_solve` method..
does it unnecessary in the `Cbc_addRow ` ?
if we use like that:
for loop: `Cbc_addCol`
for loop: `Cbc_addRow`
`Cbc_solve`

**Comment by zhengdi1992** [comment]
of course i guarantee `Cbc_addRow ` will not add new col.. which has not `Cbc_addCol` loop first

**Comment by zhengdi1992** [comment]
```
/* Minimize x
     * s.t.     x <= -10
     * x binary */
    CoinBigIndex start[] = {0, 1};
    int rowindex[] = {0};
    double value[] = {1.0};
    double rowlb[] = {-INFINITY};
    double rowub[] = {-10};
    double collb[] = {0.0};
    double colub[] = {1.0};
    double obj[] = {1.0};
    Cbc_loadProblem(model, 1, 1, start, rowindex, value, collb, colub, obj, rowlb, rowub);
```
can i use this api to build problem? will be fast?

**Comment by h-g-s** [comment]
removed the buffer check in addRow, it seems really not necessary. 
I did  not used Cbc_loadProblem, don't know how fast is it.

**Comment by tkralphs** [comment]
I would expect that building the matrix and rim vectors yourself, then handing that data to Cbc would be much faster.

**Comment by svigerske** [comment]
Indeed, doing the Cbc_loadProblem should be fastest in some sense.
