### ISSUE TITLE
Assign parameters in command

### ISSUE THREAD

**Issue by yongkyung-oh** [coin-or/Cbc#242]
My current approach can generate several mps files. How can I set-up the running time and tolerance in the command? (i.e. time limit, tolerance and so on)

**Comment by tkralphs** [comment]
Sorry that there isn't better documentation. There is a long list of parameters that can be set either in a parameter file or on the command line. The parameters are mostly listed here:

https://github.com/coin-or/Dip/blob/master/Dip/src/DecompParam.h

To see how to set them in a parameter file, you can look at the various parameter files in the examples here (especially MILPBlock):

https://github.com/coin-or/Dip/tree/master/Dip/examples

To see how to call Dip with a paramter file, see the bash script here:

https://github.com/coin-or/Dip/blob/master/Dip/examples/MILPBlock/test.sh.in

If you have more questions after looking over those links, let me know.

**Comment by yongkyung-oh** [comment]
How can we implement CBC call-back function? Is it possible to save the solution or change variables/constraints conditions while solving large problem?

**Comment by tkralphs** [comment]
There are many examples here: https://github.com/coin-or/Cbc/tree/master/Cbc/examples.
