### ISSUE TITLE
Is CBC algorithm deterministic or stochastic?

### ISSUE THREAD

**Issue by MitjaR** [coin-or/Cbc#243]
There is some indication that CBC algorithm is random ( https://github.com/coin-or/Cbc/blob/d762a83041a32e02b5ead641c2292899c39a3fcf/Cbc/src/CbcHeuristic.cpp#L159 ). Does this mean that we can get different solutions if we set the time limit for solving? (suboptimal solutions)

**Comment by svigerske** [comment]
The random number generated used in Cbc is deterministic and it has nothing to do with the timelimit.

Of course, since running time is not deterministic, setting a time limit can lead to different solutions in repeated runs.
