### ISSUE TITLE
Order of command line arguments affects solution

### ISSUE THREAD

**Issue by Express50** [coin-or/Cbc#247]
Hi, I was using Cbc (version 2.9.9) to solve a ILP and noticed that I get different results if I change the order of arguments to `cbc.exe`.

Namely, running the following two commands gives different results:

```
> cbc.exe test.mps branch max
> cbc.exe test.mps max branch
```

Looking at the solutions for both, it seems that `max branch` gives the correct result.

I've attached the test MPS file at [test.zip](https://github.com/coin-or/Cbc/files/3510891/test.zip). Thank you for your help!

**Comment by svigerske** [comment]
The command line arguments are applied from left to right. "branch max" should first solve the problem and then change the objective sense to maximization. "max branch" should first change the objective sense to maximization and then solve the problem.
Different objective sense can give different solutions.
