### ISSUE TITLE
Cbc_deletemodel leads ntdll issue

### ISSUE THREAD

**Issue by rorisimo** [coin-or/Cbc#251]
Description:
O/S: Windows 10.
COIN CBC version 2.10.0.
Work around: comment out Cbc_deletemodel. 
--
COIN CBC is producing correct results. When retrieved into application structures, the program crashes when running Cbc_deletemodel. This is happening on gutsOfDelete  when attempting to delete[] ColumnActivity_;

>	ntdll.dll!RtlReportCriticalFailure()	Unknown
 	ntdll.dll!RtlpHeapHandleError()	Unknown
 	ntdll.dll!RtlpHpHeapHandleError()	Unknown
 	ntdll.dll!RtlpLogHeapFailure()	Unknown
 	ntdll.dll!RtlFreeHeap()	Unknown
 	ucrtbase.dll!_free_base()	Unknown
 	osi_uc.exe!ClpModel::gutsOfDelete(int type) Line 171	C++
 	osi_uc.exe!ClpModel::~ClpModel() Line 160	C++
 	osi_uc.exe!ClpSimplex::~ClpSimplex() Line 542	C++
 	[External Code]	
 	osi_uc.exe!OsiClpSolverInterface::~OsiClpSolverInterface() Line 4921	C++
 	[External Code]	
 	osi_uc.exe!CbcModel::~CbcModel() Line 6679	C++
 	[External Code]	
 	osi_uc.exe!Cbc_deleteModel(Cbc_Model * model) Line 463	C++

**Comment by h-g-s** [comment]
Could you try with the current development version ?  I think that with coin brew it is easy to try.

**Comment by svigerske** [comment]
Closing as no response.
