### ISSUE TITLE
Build static executable on Linux

### ISSUE THREAD

**Issue by tkralphs** [coin-or/Cbc#256]
I would like to be able to build a fully static executable in Linux and am so far unable to do so. @SanPen has been able to do so and I'm trying to figure out exactly how. See previous conversation in the comments of #252 .

**Comment by aaalgo** [comment]
I just achieved this today with the following:

1. I manually built all of {CoinUtils, Osi, Clp, Cgl} with `configure --enable-static --disable-shared`.
To make my life easier, I didn't use any libraries fetched by coinbrew in the `ThirdParty` directory.

2. I manually built with Cbc with `configure --enable-static --disable-shared`
This one generates a `cbc` binary linked to a bunch of system libraries, but none of the coin-or libraries, so we are close to success.

3. In the building directory, in Cbc/src, I use the following command to generate a fully static `cbc`
```
# You'll need to replace my local paths. Basically add all the libraries.
g++ -static -O2 -DNDEBUG -o cbc cbc-CoinSolve.o  ./.libs/libCbcSolver.a -L/home/wdong/shared/coinor/sdist/lib -L=/lib /home/wdong/shared/coinor/sbuild/Cbc/src/.libs/libCbc.a ./.libs/libCbc.a /home/wdong/shared/coinor/sdist/lib/libCgl.a /home/wdong/shared/coinor/sdist/lib/libOsiClp.a /home/wdong/shared/coinor/sdist/lib/libClp.a /home/wdong/shared/coinor/sdist/lib/libOsi.a /home/wdong/shared/coinor/sdist/lib/libCoinUtils.a /home/wdong/shared/coinor/sdist/lib/libopenblas.a -llapack -lz -lreadline -ltinfo -pthread -lrt
```
I also built a static openblas lib from source with threading disabled for this. With palatalization enabled on the cbc level, parallel blas probably only makes it worse.

I have the binary hosted here if you are interested to try: http://www.wdong.org/~wdong/cbc.bz2

**Comment by tkralphs** [comment]
@aaalgo Great! Thanks for putting me back on the trail. I did also finally manage to get a fully static executable, but I had to do some additional stuff. Finally, I got it 95% working using `coinbrew`. Here is my recipe:
```
coinbrew build Cbc --no-prompt --no-third-party --enable-static --disable-shared --without-lapack --disable-readline --disable-bzlib CXXFLAGS="-static -O2 -DNDEBUG"
cd build/Cbc/master/src
../libtool  --tag=CXX   --mode=link g++  -all-static -static -O2 -DNDEBUG   -o cbc cbc-CoinSolve.o libCbcSolver.la libCbc.la
```
That finally produced a static executable! It's possible that I may be able to add some of the third party libraries back in eventually, but they were causing problems with static linking earlier so I disabled them and that worked.

Passing `-all-static` to libtool was the final key (see the very last line of [this page](https://ftp.gnu.org/old-gnu/Manuals/libtool-1.4.2/html_chapter/libtool_3.html)) because `libtool` was stripping out the `-static` when doing the linking (you don't have this trouble if you call `g++` directly). But the one thing I can't do yet is pass the `-all-static` flag through to `libtool` by just setting `configure` flags. I think the proper way to do it is something like adding 
```
cbc_LDADD = -all-static
```
in `src/Makefile.am` (see [here](https://www.gnu.org/software/automake/manual/html_node/Libtool-Flags.html)). @svigerske what do you think of adding a flag to `configure` that adds in that flag to `libtool.` I'm not sure why `libtool` makes this so difficult. 

@stumitchell @h-g-s Linking you in to make you aware.

**Comment by svigerske** [comment]
@tkralphs Important key! That's what I was missing, too.

We have variable LT_LDFLAGS that is used for libtool flags. It was used only when building libraries, but should be ok to use this executables, too (it generates a warning if version-info is set, though).

I don't think we intended LT_LDFLAGS to be initialized by users, but it's possible and I can get a static clp binary on my system via
```
coinbrew build Clp --no-prompt --disable-shared --without-cholmod --without-amd --disable-readline --disable-bzlib --no-third-party --without-lapack LT_LDFLAGS=-all-static 
```
I believe that Cbc should be the same.

**Comment by tkralphs** [comment]
Hmm, that didn't work for me. I called `coinbrew`, as you did and here is the top of `config.log`.
```
~/Projects/build-static/Cbc/master > more config.log
This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by Cbc configure trunk, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ /mnt/c/Users/tkral/Documents/Projects/Cbc/Cbc/configure --disable-dependency-tracking --prefix=/mnt/c/Users/tkral/Documents/Projects/dist LT_LDFLAGS=-all-static --without-cholmod --with-coin-instdir=/mnt/c/Users/tkral/Documents/Projects/dist --disable-bzlib --without-lapack --enable-static --disable-readline --disable-shared --without-amd
```
So far, so good. In `config.status`, I have 
```
S["LT_LDFLAGS"]="-all-static -no-undefined"
```
But the link command for Cbc is
```
/bin/bash ../libtool  --tag=CXX   --mode=link g++  -O2 -DNDEBUG   -o cbc cbc-CoinSolve.o libCbcSolver.la libCbc.la
libtool: link: g++ -O2 -DNDEBUG -o cbc cbc-CoinSolve.o  ./.libs/libCbcSolver.a -L/mnt/c/Users/tkral/Documents/Projects/dist/lib/pkgconfig/../../lib/mnt/c/Users/tkral/Documents/Projects/build-static/Cbc/master/src/.libs/libCbc.a ./.libs/libCbc.a -lrt -lpthread /mnt/c/Users/tkral/Documents/Projects/dist/lib/libCgl.a /mnt/c/Users/tkral/Documents/Projects/dist/lib/libOsiClp.a /mnt/c/Users/tkral/Documents/Projects/dist/lib/libClp.a /mnt/c/Users/tkral/Documents/Projects/dist/lib/libOsi.a /mnt/c/Users/tkral/Documents/Projects/dist/lib/libCoinUtils.a -lz
```
No `-all-static`. I built from scratch. Any ideas?

**Comment by svigerske** [comment]
Did you update your Cbc checkout, too?

**Comment by tkralphs** [comment]
Ah, I thought that variable was already exported. OK, will update and try again.

**Comment by tkralphs** [comment]
Great, this works! Unfortunately, it seems statically linked binaries are not supported on OS X, but using gcc and adding `CXXFLAGS="-static -static-libgcc -static-libstdc++"`, I got very close.
```
OSX: ~/Projects/dist/bin> otool -L cbc
cbc:
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
```
I guess that would be enough that it should work if moved to another OS X box with the same OS version. But anyway, there is [Homebrew](https://github.com/coin-or-tools/homebrew-coinor) for OS X, which makes it easy enough to install COIN-OR projects. For posterity, here is the full recipe.
```
OSX: ~/Projects> coinbrew build Cbc --no-prompt --parallel-jobs 4 -b build-static --no-third-party --enable-static --disable-shared --without-lapack --disable-readline --disable-bzlib --without-cholmod --without-amd LT_LDFLAGS=-all-static CXX=g++-9 CC=gcc-9 CXXFLAGS="-static -static-libgcc -static-libstdc++"
```
And with that, this issue is finally closed!

**Comment by tkralphs** [comment]
[_Edited for change in coinbrew argument_]

For posterity, there is now an option `--static` to `coinbrew` that automatically adds the options necessary for creating fully static executables. Your mileage may vary.

**Comment by tkralphs** [comment]
There are also  fully static executables for Linux available here:
https://bintray.com/coin-or/download/download_file?file_path=Cbc-master-static-linux-x86_64-gcc7.tgz

**Comment by fgenoese** [comment]
> For posterity, there is now an option `--fully-static` to `coinbrew` that automatically adds the options necessary for creating fully static executables.

Looks like it was renamed to  `--enable-static`

Thanks for setting it up @tkralphs
