### ISSUE TITLE
can not run mip solver in macos Mojave 10.14.6

### ISSUE THREAD

**Issue by zhengdi1992** [coin-or/Cbc#257]
i wanner build a java wrapper for cbc can slove mip problem..
i have choose swig such `jcbc`  、 `javacpp` 、`google or-tools`
but all occur the same problem...
lp problem works well.
mip problem all crash down the process..

only works well in linux-x64.. so any bug in macos Mojave 10.14.6?
or any other compile param should add first?

**Comment by tkralphs** [comment]
You'll have to state the problem you are having more clearly and include all relevant details, including exactly how to replicate it. There's no way to help from what you've said here. There have been a number of recent efforts to create Java wrappers for Cbc, so perhaps someone with experience can help.

**Comment by tkralphs** [comment]
@svigerske There is a macro `AC_PROG_MKDIR_P` (https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/Particular-Programs.html) for determining if there is a thread-safe `mkdir -p`, but we are not using it, as far as I can see. Nevertheless, `MKDIR_P` seems to be getting set somehow. Do you know anything about it?

**Comment by zhengdi1992** [comment]
for example..wrapper by or-tools
ref this https://developers.google.com/optimization/install/java/source_mac
`make third_party` `make java` `make java_test` all is successfully...
change the or-tools makefile use my cbc 
UNIX_CBC_DIR=~/or/coin-repo/Cbc-2.10.3/build

others i have try to use 2.10.3 cbc which clone for git `releases/2.10.3`
and buildtool `stable/0.8`
`BuildTools/get.dependencies.sh fetch`  and install it successfully

in the or-tools sample..
https://github.com/google/or-tools/blob/stable/ortools/linear_solver/samples/SimpleMipProgram.java
works bad.. output only exit 132 without anythings just crash the java process
```
Number of variables = 2
Number of constraints = 2
Process finished with exit code 132 (interrupted by signal 4: SIGILL)
```

any version will i choose wrong by cbc / buildtools?

**Comment by zhengdi1992** [comment]
like this lp problem  https://github.com/google/or-tools/blob/stable/ortools/linear_solver/samples/SimpleLpProgram.java
and change to use `CLP_LINEAR_PROGRAMMING` means use only use clp part of coin, it works well, 

but can only solve the lp problem...

**Comment by tkralphs** [comment]
As far as I know, the `or-tools` come with Cbc pre-bundled, which may be why the page you referred to doesn't actually include instructions on how to build with Cbc. This seems like a question for the maintainers of `or-tools, who must have successfully built these examples and run them with Cbc themselves (the MIP solver hard-coded in the example is Cbc). I don't have any experience with the `or-tools`.

**Comment by zhengdi1992** [comment]
i make it, the jvm param `-Xss` was the real crash reason..   default maybe not suitable.. change -Xss2048k
it run well
