### ISSUE TITLE
Cbc output

### ISSUE THREAD

**Issue by nfzhou** [coin-or/Cbc#258]
We are adding Cbc as an underlying MIP solver for Picat (picat-lang.org). Picat is a constraint logic language that has a high-level constraint interface and several underlying solvers, including CP, SAT, MIP, and SMT solvers. Currently, Picat supports two MIP solvers (Gurobi and Glpk), and communicates with them through files. As Cbc is freely available and is fast, we are considering adding it as a primary MIP solver.

We have encountered an issue. When using the command

cbc LPFile solve solu SolFile

Cbc does not output bindings of all the variables in a solution. For example, the following gives an LP file generated by Picat and the output given by Cbc:

http://picat-lang.org/tmp/3_jugs.lp
http://picat-lang.org/tmp/3_jugs.sol

With the bindings in the solution file, Picat is unable to return the solution to the original problem variables. Is there a command line option that makes Cbc output bindings of all variables?

**Comment by jjhforrest** [comment]
Use
cbc LPFile -solve -printing all -solu SolFile

**Comment by nfzhou** [comment]
Thanks! Is it ok to assume that the value for a variable is 0 if variable does not occur in the output?

**Comment by tkralphs** [comment]
Yes, variables not occurring should have value zero.
