### ISSUE TITLE
Windows binaries compiled with /MD flag

### ISSUE THREAD

**Issue by optivation-lfm** [coin-or/Cbc#259]
Currently the windows Cbc binaries provided through bintray is compiled with the VS /MT flag. This means that these can not be linked with other binaries compiled with the /MD flag.

It would be great if the binaries on bintray would also include ones compiled with /MD.

**Comment by tkralphs** [comment]
I have now switched all the binaries built from master to be compiled with the /MD flag. Can you give them a try?

**Comment by optivation-lfm** [comment]
I have tried Cbc-master-win32-msvc15.zip downloaded from: https://bintray.com/coin-or/download/Cbc/master

It links in visual studio 2017 now against release binaries compiled with /MD flag :) Thanks!

I would suggest also providing the old /MT compiled binaries to be as general as possible (and the corresponding debug binaries for both /MT and /MD).

**Comment by tkralphs** [comment]
It would be easy to also build with /MT, /MTd, and /MDd, but we have limited build time on the open source plan and no budget. I'll give it a try.

**Comment by optivation-lfm** [comment]
Ok sounds good!

**Comment by tkralphs** [comment]
OK, now there are binaries built from master and compiled with /MT, /MD, /MTd, /MDd with Visual Studio Versions 2015, 2017, and 2019. I guess that should cover it for now! At some point soon, this setup will also move to stable/2.10, which may be more useful.

**Comment by optivation-lfm** [comment]
Perfect! Thanks!
