### ISSUE TITLE
Debian package(s) orphaned

### ISSUE THREAD

**Issue by tkralphs** [coin-or/Cbc#263]
The Debian packages for Cbc and other COIN-OR projects have been orphaned. 

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=934084

Add a comment if you would like to help. Everything is set up already, the time commitment should be small.

**Comment by h-g-s** [comment]
Wow, this is not good. I'll see if I find time for this.

**Comment by tkralphs** [comment]
OK, great, some others have reached out off-line so we can probably put together a team.

**Comment by tkralphs** [comment]
@SnarkBoojum has now taken over the Debian packages (see #314). Thanks!
