### ISSUE TITLE
undefined behaviour in CbcModel.cpp

### ISSUE THREAD

**Issue by tosttost** [coin-or/Cbc#265]
CbcModel::addCutGenerator and  CbcModel::addHeuristic call memcpy(pointer, NULL, 0) if the first cut generator / heuristic is added. 
according to https://en.cppreference.com/w/cpp/string/byte/memcpy : "If either dest or src is a null pointer, the behavior is undefined, even if count is zero. "

Although it is unlikely that any implementation of memcpy gets this wrong some compiler conclude that any pointer passed to memcpy is not NULL and e.g. "optimize" NULL-checks away.

There are 2 ways to fix this:
* check if the old array is NULL and skip memcpy
* store the heuristics / cut generators inside std::vector
   * this would simplify the code, e.g. the "//move up" loop and storing the count  get unnecessary.
   * might require trivial modifications in other methods.

I can create a PR as soon as I know which way this should be fixed. I'd go with std::vector ;)

**Comment by svigerske** [comment]
I went with the less invasive way of checking source for NULL. I don't really like switching just 2 of the arrays in CbcModel to STL containers and leave the rest as they are.
