### ISSUE TITLE
Compatibility for C++17?

### ISSUE THREAD

**Issue by andreacassioli** [coin-or/Cbc#266]
Hi,
It seems Cbc code is not C++17 compliant. For instance, I have tried to switch from C++14 to C++17 and got 

```
/usr/local/opt/coinutils/include/coinutils/coin/CoinHelperFunctions.hpp:44:11: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
CoinCopyN(register const T* from, const int size, register T* to)
```

Even thought not still common, C++17 has quite nice features and people might start to try it out soon. 

Are there any plan to make the code complaint with the recent standard?

**Comment by tkralphs** [comment]
We have discussed this and for a number of reasons, we do not want to introduce features that require C++17 (portability, etc.). But we can certainly fix things like not using `register`, and try to make the code compliant with C++17. We have already done this in some places.  It would be helpful to have a PR.

**Comment by svigerske** [comment]
`register` was already removed years ago, e.g., https://github.com/coin-or/CoinUtils/commit/4f0dab267fc3976d0542f56e2939f900857147a6#diff-19876450ddca2bf5fe8d81ac25f0caa5

**Comment by andreacassioli** [comment]
@svigerske my bad, I did not realised that the issue is actually with `coinutils`! I'll repost the issue on that repo.

**Comment by svigerske** [comment]
It was fixed in CoinUtils years ago.
