### ISSUE TITLE
Binaries for parallell execution

### ISSUE THREAD

**Issue by BjornSigurd** [coin-or/Cbc#270]
Please provide cbc.exe binaries providing the possibility to optimize in parallel.  I.e. where the run time option "-threads" may be used to specify the maximum number of threads the optimization may utilize.

**Comment by joaotavora** [comment]
I'm very sorry for coming here just to say +1, but +1 :-) This would be very welcome.

**Comment by tkralphs** [comment]
Building binaries that run in parallel with the Visual Studio is a bit involved and may have to wait. However, if all you need is a binary (and not libraries) that runs in parallel on Windows, I have successfully built one with the MinGW compilers. A test binary will appear on Bintray shortly. I will follow up when it does. That should satisfy your needs.

**Comment by joaotavora** [comment]
> However, if all you need is a binary (and not libraries) that runs in parallel on Windows, I have successfully built one with the MinGW compilers.

I the meantime, I can confirm this, too.  Thanks.

**Comment by tkralphs** [comment]
The MinGW binaries for master on bintray should now run in parallel on Windows. They work for me, but if anyone can give it a try, that would be helpful. Download [here](https://bintray.com/coin-or/download/download_file?file_path=Cbc-master-x86_64-w64-mingw32.zip) (64-bit).

**Comment by tkralphs** [comment]
I realized there are some dependencies that are not bundled. I'm trying to fix that now.

**Comment by BjornSigurd** [comment]
Yes, I can confirm that if I try running cbc.exe posted yesterday/Friday 4:25 PM, I get the error “The code execution cannot proceed because liblapack.dll was not found. Reinstalling the program may fix the problem.”.

Best,
Bjorn Sigurd

**Comment by tkralphs** [comment]
It should be fixed now, all dependencies are bundled. The 64-bit binaries have been built and uploaded. Please give it a try!

**Comment by BjornSigurd** [comment]
Not working.  The dll   libbz2-1.dll  is missing.

[cid:image001.png@01D59D87.C2FE01F0]


Best,
Bjorn

**Comment by tkralphs** [comment]
That is fixed, can you try again?

**Comment by BjornSigurd** [comment]
Hi,

Ted, I not get message about missing libwinthread-1.dll after having downloaded latest from https://bintray.com/coin-or/download/download_file?file_path=Cbc-master-x86_64-w64-mingw32.zip


Best,
Bjorn

**Comment by BjornSigurd** [comment]
Hi,

Ted, I not get message about missing libwinpthread-1.dll after having downloaded latest from https://bintray.com/coin-or/download/download_file?file_path=Cbc-master-x86_64-w64-mingw32.zip


[cid:image001.png@01D5A13C.7B27E720]

Best,
Bjorn

**Comment by BjornSigurd** [comment]
Hi,

Ted, I also get warned about  libstdc++-6.dll.

[cid:image002.png@01D5A13C.C9E51180]


And libquadmath-0.dll

[cid:image003.png@01D5A13C.C9E51180]

Best,
Bjorn

**Comment by BjornSigurd** [comment]
Hi again!  Any chance of including libstdc++-6.dll and libquadmath-0.dll in the download?

**Comment by tkralphs** [comment]
Sorry, I meant to follow up---I did correct this and the latest binaries should come with those DLLs. Hopefully, these will be the last ones needed! Please let me know what you have the chance.

**Comment by BjornSigurd** [comment]
Working now, great, thx. : )
https://bintray.com/coin-or/download/download_file?file_path=Cbc-master-x86_64-w64-mingw32.zip

Some stats:

  *   When compared to my previous cbc.exe (appr. version 2.9.8), single threaded optimization times are improved from 164  to 66 seconds(!) on my MIP case.  (Exact same solution is found).

Peak memory consumption reduced slightly from 61 KB to 56KB.

  *   When running with option -threads 8 on my 8 CPU machine, 5-6 CPUs are utilized in average and running time is reduced from 66 seconds to 54/35/51 (average 47 seconds).  Peak RAM consumption increased from 56KB to 171KB.
  *   When running with option -threads 4 on my 8 CPU machine, 4 CPUs are utilized and running time is reduced from 66 seconds to 35/52/73 (average 53).
Note that the running times when using threads (both 4 and 8) fluctuates quite a lot.
Conclusion on my MIP case:
The good: The new cbc.exe version is more than twice as fast as my previous version.
The not so good:  Using threads 4 or 8 does not reduce running time very much.

Suggestions:

  *   Avoid RAM (de-allocation): Especially when running single thread, the “Kernel times” (may be seen in TaskManager >CPU) are very high – about 50% of total CPU consumption.  In my experience Kernel time for optimization SW is generated due to memory allocation and deallocation.  If CBC could avoid all (de-)allocation of RAM, running speed could be doubled.  RAM (de-)allocation is avoided by re-using arrays and objects, for instance by putting arrays at a more global level and/or passing re-used arrays as member parameters. Remember that it is normally much faster to clear an existing array than creating a new one.  (C# and probably C++ have separate functions for massive array operations, e.g. “Buffer.BlockCopy()”) Also, static arrays may be utilized (depending on programming language).  This will normally result in a slightly worse structured program needing some more comments, but will be more than compensated with increased running speed.
  *   32 bit exe?: The given cbc.exe have a very moderate RAM consumption, and need not be 64 bit compiled.  Executables 32 bit compiled are to my (but not to every other) knowledge quite a bit faster than 64 bit:  The executable gets smaller, hence more of it fit in the L2 RAM cache, and having less available address space may improve running speed on top of that. Testing the speed of a 32 bit compiled exe may be worth-while.
  *   Multi-thread improvement?  Seems to me as if the parallel (i.e. “thread”) functionality could be improved:  First, using “threads” only improves running speed moderately (at least on my MIP test case), and also the running times fluctuates quite a lot.  (Some fluctuation is to be expected and may even be a good sign, but when there is this much fluctuation, one might expect that some sort of “tightening” could/should be applied).

Best,
Bjorn

**Comment by h-g-s** [comment]
Hi Bjorn,

Make the parallel code efficient is really hard:

https://symposia.cirrelt.ca/system/documents/000/000/111/Bixby_original.pdf?1441306917

It seems that the most important search phases (such as presolve) are 
inherently sequential.

So, Bixby says in his presentation:

"Our conclusion: 2x improvement for p=4 is about the most we can expect 
(3x seems a reasonable guess forp=8)"

BTW, could you share your MIPs ? I run periodically some benchmarks in CBC.

**Comment by BjornSigurd** [comment]
Hi Heraldo,

Attached is my MIP.
Please feel free to run it as hard as you like.  : )
Any improvement comments welcomed.



  *   Bjorn

**Comment by tkralphs** [comment]
@BjornSigurd 32-bit MinGW binaries are also available [here](https://bintray.com/coin-or/download/download_file?file_path=Cbc-master-i686-w64-mingw32.zip) and I would appreciate it if you would also test them (I added the 32-bit versions of the same DLLs to those packages, so I hope they should work).

As @h-g-s indicated, parallelizing a MIP solver is challenging. The moderate speed-up and fluctuations you experienced are the norm and to be expected. If you want to know a lot more about the reasons for that, here are several papers that go into a lot of detail about it:
-   http://coral.ie.lehigh.edu/~ted/files/papers/Million11.pdf
-   http://coral.ie.lehigh.edu/~ted/files/papers/ParallelMILPSurvey16.pdf
-   http://coral.ie.lehigh.edu/~ted/files/papers/ParallelAssessment19.pdf

**Comment by h-g-s** [comment]
I think you forgot to attach it.

**Comment by BjornSigurd** [comment]
Hmm, I did attach it on my side..
Lets try again.
I will also send a second mail where i try pasting the whole model into the Email.

**Comment by BjornSigurd** [comment]
https://gist.github.com/tkralphs/ac8490ed2f560d81b14cdfb5bbfc2d3f

**Comment by BjornSigurd** [comment]
Hi Ted,

Not able to run 32 bit version.  (Tried the download link twice).
Got message “The application was unable to start correctly (0xc000007b).”

[cid:image001.png@01D5A717.C920BCF0]


I then tested on another PC, which gave message on missing zlib1.dll:

[cid:image002.png@01D5A71A.C40974C0]




  *   Bjorn

**Comment by BjornSigurd** [comment]
Haroldo,

Perhaps the attachment was too large (413 KB).
Please try downloading from here:
https://s3-eu-west-1.amazonaws.com/download.spidersolutions.no/Projects/LargeScale/Model___20.56.24.803___ToCbc.lp


  *   Bjorn

**Comment by h-g-s** [comment]
Downloaded! Thanks.
