### ISSUE TITLE
CBC add-on function or module

### ISSUE THREAD

**Issue by yongkyung-oh** [coin-or/Cbc#272]
I'm working on MIP preprocess and presolve technique using python. (Python-mip: https://python-mip.readthedocs.io/en/latest/)

At this moment, I would like to add the function to the cbc solver. For example, add a parameter to call the function script. I will rewrite the original code into c++ if needed. Is there any guideline or suggestion for this approach? 

Thanks.

**Comment by tkralphs** [comment]
Sorry for not getting back to you at the time. There really isn't any sort of developer's guide, but feel free to make a PR!
