### ISSUE TITLE
Inconsistent solution for problem with large coefficients

### ISSUE THREAD

**Issue by s-wegener** [coin-or/Cbc#280]
Hi there,

for the attached test case, the computed result value of the objective function (26227592278887364) is inconsistent with the sum of its terms, which is 26227592278887352.

[test.zip](https://github.com/coin-or/Cbc/files/4015417/test.zip)

**Comment by h-g-s** [comment]
Hi,  Linear Programming based solvers operate with limited precision (64 bits floating point) and very large/very small values are expected to give trouble. There are several parameters for tolerances that you should try if you plan to use these values:  integerTolerance  ,   dualTolerance    and   primalTolerance  -  usually you have some safety up to the 6th  decimal place.

**Comment by s-wegener** [comment]
Ok, thank you for the informative answer.
