### ISSUE TITLE
pkgconfig files on bintray are not relocatable

### ISSUE THREAD

**Issue by mkoeppe** [coin-or/Cbc#281]
The bintray tarballs are shipped with `pkg-info` files in `lib/pkgconfig` that set `prefix=/home/travis/build/coin-or/dist`. This should be changed to `prefix=${pcfiledir}/../..`.
In my install scripts I'm just fixing it up with 
```
sed -i.bak 's|^prefix=/home/travis/.*|prefix=${pcfiledir}/../..|' *.pc 
```
but it would be better if this was already shipped correctly in the binary distribution.

**Comment by svigerske** [comment]
We install the .pc files into `$libdir/pkgconfig`, where `libdir` defaults to `$exec-prefix/lib` or `$exec-prefix/lib64` and `exec-prefix` defaults to `$prefix`.
So if some user set a different libdir, then prefix may not be `$pcfiledir/../..` anymore.
Is there some nice way to handle this?

@tkralphs Maybe one should postprocess the .pc files that are uploaded by appveyor and travis only? In that case, one knows that libdir hasn't been changed.

**Comment by mkoeppe** [comment]
Perhaps you could add an option `--enable-relocatable` to the build systems that turns on this behavior. Better than adding special magic to deployment scripts.

**Comment by svigerske** [comment]
I can actually check whether libdir looks like the default and only then use `$pcfiledir/../..` in .pc files.
This won't go into any of the existing stable branches, but the next major release only.

**Comment by svigerske** [comment]
There was some resistance to have `$pcfiledir/../..` automatically if valid, because it creates libtool warnings when building against installed libraries, as the paths in the .la do not match anymore.
So there will be an `--enable-relocatable` to enable this manually.

**Comment by mkoeppe** [comment]
I also prefer this solution. Thanks for your work on this!

**Comment by tkralphs** [comment]
An alternative that I would like to mention here for posterity is to simply over-write the prefix flag manually.
```
pkg-config --define-variable=prefix=/foo
```
I guess this may not be as convenient (or even discoverable for those who don't know to look for it), but it works after the fact, even if the original `.pc` files were not made relocatable. It's good to keep in mind.

**Comment by mkoeppe** [comment]
Yes, that is a workaround that sometimes helps. But in general, relying on setting package-specific options to pkg-config is not an option for a build system, and in a sense defeats the purpose of pkg-config.

**Comment by tkralphs** [comment]
Hmm, I didn't think of this work-around as "package-specific". Do you mean because not all packages use the `prefix` variable to define paths, so it may not always work? Seems like it should work for any package that has a properly structure `.pc` file. 

I guess I'm hesitant because defining the prefix to be relative to the location of the `.pc` file strikes me as a little fragile. It means you can relocate the entire installation as a whole, but not the `.pc` file itself. Over-riding `prefix`, on the other hand, also allows for the `.pc` file itself to be relocated relative to the rest of the installation. 

I guess if you're just grabbing the zip from bintray and want to unzip it anywhere and have it work, then a relative path is a good solution. Since you can still over-ride the `prefix`, even in that case, maybe it is the best way to go, just looks a little ugly. Anyway, food for thought.

**Comment by mkoeppe** [comment]
> Hmm, I didn't think of this work-around as "package-specific". 

Package BAB needs to link against CBC and DCD, each of which happen to be installed from binary distributions in separate prefixes /opt/CBC and /opt/DCD and use the prefix variable in their .pc files /opt/CBC/lib/pkg-config/libcbc.pc and /opt/DCD/lib/pkg-config/libdcd.pc. The user sets  PKG_CONFIG_PATH and now invokes the configure script of BAB, which calls pkg-config to find CBC and DCD.  Now to override the pc file prefixes, the user would have to edit the configure script. 

> I guess I'm hesitant because defining the prefix to be relative to the location of the `.pc` file strikes me as a little fragile. It means you can relocate the entire installation as a whole, 

Yes, that's what --enable-relocatable means. The whole installation into prefix can be moved to a new prefix.

> I guess if you're just grabbing the zip from bintray and want to unzip it anywhere and have it work, then a relative path is a good solution. 

isn't this how one uses a binary distribution?

**Comment by tkralphs** [comment]
> isn't this how one uses a binary distribution?

Yes, although this is not documented anywhere and I'm sure someone will figure out a way to do otherwise. Really, though, this fix just offends my sensibilities somehow :). I'll find a way to get over it eventually.
