### ISSUE TITLE
fatal: unable to access 'https://github.com/coin-or/-–test/': The requested URL returned error: 400

### ISSUE THREAD

**Issue by jczazueta** [coin-or/Cbc#294]
Hi,
I am installing Cbc, but appears a problem when I do:
~/coinbrew-master/coinbrew build Cbc -–prefix=/home/jzazueta/lib -–test
Displays:
Welcome to the COIN-OR fetch and build utility

For help, run script with --help.

Entering interactive mode (suppress with --no-prompt)...

It appears that project has not been fetched yet.
Fetching automatically...
fatal: unable to access 'https://github.com/coin-or/-–test/': The requested URL returned error: 400

It seems strange, because yesterday was working ok.

May you help?

Best Regards.
Juan Carlos

**Comment by tkralphs** [comment]
Wow, this was a strange bug. Believe it or not, I finally figured out that there are stray characters in your command above that was wreaking havoc somehow. If you look carefully at -–prefix above, you will see that the second "-" is not the same character as the first "-" (it is a bit longer). The same is true with "-–test". 

I don't know where it came from but when I copied your command verbatim, I saw the same behavior, but typing it myself, it worked! Just replace the second "-" with the same character as the first and it should work. If you copied this from some documentation somewhere, let us know so we can fix it!

**Comment by jczazueta** [comment]
You are so right, my mistake. I take it from a document in word and it   it.
Well now run, but there is other problem as you see
##################################################
### Building CoinUtils master 
##################################################

In file included from /usr/include/c++/4.8.2/algorithm:62:0,
                 from /home/jzazueta/dependencies/CoinUtils/src/CoinBronKerbosch.cpp:2:
/usr/include/c++/4.8.2/bits/stl_algo.h: In instantiation of ‘_RandomAccessIterator std::__unguarded_partition(_RandomAccessIterator, _RandomAccessIterator, const _Tp&, _Compare) [with _RandomAccessIterator = BKVertex*; _Tp = BKVertex; _Compare = bool (*)(BKVertex&, const BKVertex&)]’:
/usr/include/c++/4.8.2/bits/stl_algo.h:2296:78:   required from ‘_RandomAccessIterator std::__unguarded_partition_pivot(_RandomAccessIterator, _RandomAccessIterator, _Compare) [with _RandomAccessIterator = BKVertex*; _Compare = bool (*)(BKVertex&, const BKVertex&)]’
/usr/include/c++/4.8.2/bits/stl_algo.h:2337:62:   required from ‘void std::__introsort_loop(_RandomAccessIterator, _RandomAccessIterator, _Size, _Compare) [with _RandomAccessIterator = BKVertex*; _Size = long int; _Compare = bool (*)(BKVertex&, const BKVertex&)]’
/usr/include/c++/4.8.2/bits/stl_algo.h:5499:44:   required from ‘void std::sort(_RAIter, _RAIter, _Compare) [with _RAIter = BKVertex*; _Compare = bool (*)(BKVertex&, const BKVertex&)]’
/home/jzazueta/dependencies/CoinUtils/src/CoinBronKerbosch.cpp:343:70:   required from here
/usr/include/c++/4.8.2/bits/stl_algo.h:2266:34: error: invalid initialization of reference of type ‘BKVertex&’ from expression of type ‘const BKVertex’
    while (__comp(__pivot, *__last))
                                  ^
make[2]: *** [CoinBronKerbosch.lo] Error 1
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1

Build failed, see error output above
----
But I will put it in a new Issue.

Regards
Juan Carlos

**Comment by tkralphs** [comment]
Yes, Word will auto-correct -- to a long dash, you definitely should not copy commands into Word and then back out again.
