### ISSUE TITLE
CBC misinterprets warmstart with maximization problems

### ISSUE THREAD

**Issue by zaverna** [coin-or/Cbc#296]
Hello everyone!

We've been using CBC for our use case and sincerely thank the team for their dedication to the project!

Unfortunately, we have to report the following issue. 

In our use case we are trying to solve a maximization problem. 
We then provide a suboptimal warm start to CBC.
However, CBC seems to interpret the value of the warm start "with the wrong sign" and also ends up failing to correctly compute the LP relaxation of the model, yielding huge floats, with the wrong sign as well.

The weird behaviour can lead to the solver halting prematurely and incorrectly yielding the warm start solution as an optimal one, but with the wrong objective sign, or to take much longer to solve the problem as the misinterpreted warm start leads the solver "in the wrong direction".

The issue does not appear with minimization problem. We think there could be some mistake in the handling of signs from reading the warm start to transforming the max problem into a min problem.

We cannot share data about our use case due to privacy and IP concerns.

We recreated the issue with CBC 2.10.5 (stable at the moment of writing the ticket) and the classic bin packing problem.

Please see the attachment.
[CBC_mipstart_error_maximization_example.zip](https://github.com/coin-or/Cbc/files/4455567/CBC_mipstart_error_maximization_example.zip)

cheers

Andrea

**Comment by jjhforrest** [comment]
The change below has been checked in - should fix problem.

--- CbcSolver.cpp	(revision 2981)
+++ CbcSolver.cpp	(working copy)
@@ -5889,6 +5889,13 @@
                      babModel_->createContinuousSolver();
                      babModel_->setBestSolution(CBC_ROUNDING,
                        obj, &x[0], 1);
+		    /* But this is outside branchAndBound so needs to know
+		       about direction */
+		    if (babModel_->getObjSense()==-1.0) {
+		      double increment = obj-babModel_->getCutoff();
+		      babModel_->setCutoff(-obj-increment);
+		      babModel_->setMinimizationObjValue(-obj);
+		    }
                      babModel_->clearContinuousSolver();
                      babModel_->passInSolverCharacteristics(NULL);
                      if (useSolution == 0)

**Comment by tkralphs** [comment]
Fixed by c79fee9fbae47639470c6425316c3d1f26bde2b6
