### ISSUE TITLE
the purpose of OsiSolverLink

### ISSUE THREAD

**Issue by guanglei1wang** [coin-or/Cbc#297]
Hi guys, 

I have been diving into the codes of Cbc for some time.  
And I was struggling with the design of OsiSolverLink? 

It has a brief description as follows. 
/**
This is to allow the user to replace initialSolve and resolve
This version changes coefficients
*/

But still, why do we need that? 
And it seems a bit weird (from the naming) that "OsiSolverLink" inherit from CbcOsiSolver which inherits from OsiClpSolverInterface? 

Could anyone help on this? 

Best regards 
Guanglei Wang

**Comment by jjhforrest** [comment]
I will try and remember more about this.

It is to do with solving non-linear problems which have integer 
variables and/or is non convex.

Linked Ordered Sets were developed by Martin Beale in the late 1970's - 
a powerful idea which is a generalization of Special Ordered Sets 
(invented by Beale & Tomlin).  The basic idea is that a variable value 
is a linear combination of its lower and upper bounds, so if you branch 
on the two SOS for these simultaneously, you can play lots of tricks. 
It gets more complicated when you allow interpolation and that is what 
this is about.

John Forrest

**Comment by guanglei1wang** [comment]
Thanks John. 

It's much clear now.  It's good to learn the brief review as well ..

Best regards
Guanglei

**Comment by jjhforrest** [comment]
Guanglei,

There are two examples link.cpp and gear.cpp in Cbc/examples.  I think 
they are more than ten years old - I have had to fix something in 
Cbc/master to get gear.cpp to work.

Will look at interpolation i.e. OsiSolverLink - there is a comment in 
gear.cpp ------

   "The generalization with column generation can be even more powerful
but is not yet in CBC."

So it is possible that it is a half finished project.

John

**Comment by guanglei1wang** [comment]
Hi John, 
Thanks a lot for the examples. 
Yes, 'link' is compiled and running well while 'gear' has some 'nullptr' issue. 
I am wondering if you will push the fixing?

(Simply fixing TRY_STUFF 1 will do, but I will try to fix line 514 ...)

Best, 
Guanglei 

![image](https://user-images.githubusercontent.com/8190450/79450215-39c47180-8017-11ea-91b7-acf2a1291821.png)
