### ISSUE TITLE
CBC stopped running 

### ISSUE THREAD

**Issue by ShivKJ** [coin-or/Cbc#299]
Hi,

I am using CBC and it showed me the following issue:

would have 0 free columns in primal, 5 in dual
Dual of model has 89024 rows and 90489 columns
Aborted (core dumped)

Not sure what is root cause for this?
When I tried other solver, I was not getting the issue.

**Comment by h-g-s** [comment]
Could you include the MPS file ?  If the error also occurs in CBC then 
it would be much easier to debug....
