### ISSUE TITLE
C++ `minimum` example doesn't build on Ubuntu with given Makefile or documentation

### ISSUE THREAD

**Issue by JRDetwiler** [coin-or/Cbc#302]
After installing `coinor-cbc` on Ubuntu 19 like the README suggests, I tried getting the `minimum.cpp` example to work. I immediately ran into issues linking the `hpp` files it was trying to include.

Turns out I also needed the `coinor-cbc-dev` package that I happened to stumble across by tab completion. I would recommend adding this to documentation somewhere.

Even then, it wasn't able to find the include files it needed to compile. It was installed under `/usr/include/coin`, but the example `Makefile.in` was looking for a `coin-or` directory. Plus, I was using make instead of whatever that file was designed for (automake/cmake?), so that could've been a problem too.

I got the version of `minimum.cpp` [here](https://www.coin-or.org/Cbc/cbcuserguide.html#minimum.cpp) to compile after a couple of hours of trying to work with this...

    g++ minimum2.cpp -o minimum -I /usr/include/coin -l Cbc -l OsiClp

I think it might be beneficial for others to update the documentation and/or examples to streamline the installation/testing process for newcomers. I was able to find a handful of Cbc code examples, but nothing explaining how to install Cbc headers and compile the examples.

**Comment by svigerske** [comment]
The Ubuntu package and the Cbc source on master aren't compatible at all. The makefile for the examples assume that one has build and installed a Cbc library from the same source tree.

**Comment by JRDetwiler** [comment]
That's what I quickly learned, but installing the packages for my distribution was certainly the easier route of obtaining the library. I hit a wall with the documentation---I was trying to learn how to use the library, found examples, but found nothing suggesting what I needed to include or link. The files existing on the source tree were my best alternative.

**Comment by tkralphs** [comment]
The documentation is not great and thanks for the report. There is a lot of old documentation out there and we have limited bandwidth for doing lots of maintenance tasks. 

Looking at the source was the right idea, the missing link is that you need to look at the branch corresponding to the version you actually had installed. I think that's 2.9.9 on Ubuntu (another unfortunate issue is that the Debian package was orphaned a while back and we need to find someone to maintain it).  If you take a look at [stable/2.9](https://github.com/coin-or/Cbc/tree/stable/2.9), you'll find compatible examples and build files. 

But building yourself from source is probably the best way to work with Cbc on Linux these days.

**Comment by tkralphs** [comment]
Looks like 2.10 is available in Ubuntu 20, so someone updated the package. I updated the `README` to be a bit clearer about the points you raised. I'm going to close this issue.

**Comment by JRDetwiler** [comment]
> The documentation is not great and thanks for the report. There is a lot of old documentation out there and we have limited bandwidth for doing lots of maintenance tasks.

Totally understandable, and thank you!
