### ISSUE TITLE
Valgrind errors with multiple threads for version 2.10.5

### ISSUE THREAD

**Issue by yashpuranik** [coin-or/Cbc#308]
For the attached lp, the cbc executable leads to valgrind errors with the attached lp (coinlp.txt since github wont allow upload for a .lp file) file when threads is specified to 1.

Also attached are the stdout and valgrind logs. The executable was compiled from source on CentOS 7. Please let me know if more information is needed to reproduce the issue. 

[coinlp.txt](https://github.com/coin-or/Cbc/files/4719123/coinlp.txt)
[stdout.log](https://github.com/coin-or/Cbc/files/4719126/stdout.log)
[valgrind.log](https://github.com/coin-or/Cbc/files/4719127/valgrind.log)

**Comment by jjhforrest** [comment]
Not sure how important this is - only applies to threaded and SOS or 
similar - and I am not sure it makes any difference to results.  However 
I have fixed in master.

John Forrest
