### ISSUE TITLE
Random seed for multi-thread runs

### ISSUE THREAD

**Issue by DataDictator** [coin-or/Cbc#315]
Hello,

When I set "-randomSeed" and "-randomCbcSeed" options to some int values, the results of MIP solutions are consistently reproducible for single-threaded runs ("-threads 1") . This reproducibility is lost on multi-thread runs ( for example "-threads 4"), the logs show that all the "pre-processing" is consistent between different runs, but it appears if the tree searching "worker threads" still get random seeds.  

Could you please verify if this is indeed so? If yes, is it possible to derive the random seeds for the worker threads from "randomCbcSeed" using the thread index? Usually, shifting a seed even by a small number creates uncorrelated pseudorandom number sequences (at least for reasonable generators).

Having this ability to reproduce the results would allow us to easier debug some problematic cases we encounter.

**Comment by svigerske** [comment]
`-threads 4` doesn't give you a deterministic parallel tree search. Use `-threads 104` for that.

From the Cbc CLI:
```
Coin:thread??
thread(s) : Number of threads to try and use
To use multiple threads, set threads to number wanted.  It may be
better to use one or two more than number of cpus available.  If 100+n
then n threads and search is repeatable (maybe be somewhat slower),
if 200+n use threads for root cuts, 400+n threads used in sub-trees.
<Range of values is -100 to 100000;
	current 0>
```

**Comment by DataDictator** [comment]
Thanks for the help!
