### ISSUE TITLE
CBC build on ppc64-le architecture

### ISSUE THREAD

**Issue by utkarsh-kumar-1996** [coin-or/Cbc#317]
I have been trying to build CBC (branch = stable/2.9) on following environment:
**Chassis: vm
Virtualization: kvm
Operating System: CentOS Linux 7 (AltArch)
CPE OS Name: cpe:/o:centos:centos:7:server
Kernel: Linux 3.10.0-1062.4.1.el7.ppc64le
Architecture: ppc64-le**

I got the following error
`checking build system type... ./config.guess: unable to guess system type

This script, last modified 2007-05-17, has failed to recognize
the operating system you are using. It is advised that you
download the most up to date version of the config scripts from

  http://savannah.gnu.org/cgi-bin/viewcvs/*checkout*/config/config/config.guess
and
  http://savannah.gnu.org/cgi-bin/viewcvs/*checkout*/config/config/config.sub

If the version you run (./config.guess) is already up to date, please
send the following data and any information you think might be
pertinent to <config-patches@gnu.org> in order to provide the needed
information to handle your system.

config.guess timestamp = 2007-05-17

uname -m = ppc64le
uname -r = 4.15.0-76-generic
uname -s = Linux
uname -v = #86-Ubuntu SMP Fri Jan 17 17:24:13 UTC 2020

/usr/bin/uname -p = ppc64le
/bin/uname -X     = 

hostinfo               = 
/bin/universe          = 
/usr/bin/arch -k       = 
/bin/arch              = ppc64le
/usr/bin/oslevel       = 
/usr/convex/getsysinfo = 

UNAME_MACHINE = ppc64le
UNAME_RELEASE = 4.15.0-76-generic
UNAME_SYSTEM  = Linux
UNAME_VERSION = #86-Ubuntu SMP Fri Jan 17 17:24:13 UTC 2020
configure: error: cannot guess build type; you must specify one
make: *** [/thirdparty/build/make/cbc-solver] Error 1`

Then I updated the config.guess and config.sub files tp the latest (timstamp=2020-04-26) inside Cbc root folder as well as in ThirdParty libraries (ASL, Blas, Glpk, Lapack, Metis, Mumps) and configuration step was successful.

I have executed `make` command, now I am getting following error, not sure how to resolve this.

> gcc -c -O3 -pipe -DNDEBUG -DASL_BUILD  -fPIC -DPIC -DASL_NO_FPINITMT fpinit.c
> fpinit.c: In function 'fpinit_ASL':
> fpinit.c:130:30: error: '_FPU_EXTENDED' undeclared (first use in this function)
>   __fpu_control = _FPU_IEEE - _FPU_EXTENDED + _FPU_DOUBLE;
>                               ^
> fpinit.c:130:30: note: each undeclared identifier is reported only once for each function it appears in
> fpinit.c:130:46: error: '_FPU_DOUBLE' undeclared (first use in this function)
>   __fpu_control = _FPU_IEEE - _FPU_EXTENDED + _FPU_DOUBLE;

**Comment by svigerske** [comment]
Maybe an update of the ASL source would do, but if you do not need to run Cbc on AMPL .nl files, then skipping ASL (remove ThirdParty/ASL directory) might be easiest.
If you need ASL, then [this issue](https://github.com/jump-dev/Ipopt.jl/issues/86) suggests to add `ADD_CFLAGS=-DNO_fpu_control` to your configure call.
I cannot say for sure that this doesn't happen with current Cbc 2.10 or master. I don't know anyone testing on PowerPC.

**Comment by utkarsh-kumar-1996** [comment]
What does this flag specify `ADD_CFLAGS=-DNO_fpu_control ` ?

**Comment by svigerske** [comment]
I assume that having `NO_fpu_control` defined will turn off the use of `_FPU_EXTENDED`, etc, in ASL.

**Comment by utkarsh-kumar-1996** [comment]
What will be the impact of doing so on generated shared libraries?

**Comment by svigerske** [comment]
ASL isn't part of Cbc. At least I cannot say for sure what the effect will be if ASL doesn't change FPU flags. But I doubt that there would an effect for LP/MIP. You can try whether ASL developers at https://github.com/ampl/asl can say more.

**Comment by utkarsh-kumar-1996** [comment]
This step `sh BuildTools/get.dependencies.sh fetch` fetches ASL and others, are they required to build CBC?

**Comment by tkralphs** [comment]
First, the BuildTools/get.dependencies is deprecated. You should use coinbrew (follow the instructions for fetching in the README in current master, not the README in the version you are trying to build).

Is there a reason you are trying to build such an old version of Cbc? stable/2.10 is the most recent stable branch and it would be much better to use that one unless you have a specific reason not to.

WIth stable/2.10, the ThirdParty projects are optional, though you should make sure Blas and Lapack are available. It's best just to install them as packages, since you're on CentOS. ASL is only required if you want to use Cbc with AMPL.

**Comment by utkarsh-kumar-1996** [comment]
Hi Ted,

My library is dependent on another library which uses Cbc 2.9 that's why I am using the same to keep things in sync.

Thanks.

**Comment by tkralphs** [comment]
I would be surprised if you couldn't just drop in stable/2.10 instead of stable/2.9. The APIs should be nearly identical.
