### ISSUE TITLE
Non feasible solution returned whereas no feasible solution exists

### ISSUE THREAD

**Issue by sKamer73** [coin-or/Cbc#320]
Hello,

First thank you for the job, it is really useful. I'm a "newbie" regarding MIP, and I'm trying to code a simple example for my work; I hope being in the good section. 

I believe I coded it right, as I'm running the same problem in Mathematica 9.0 (and have the same issue). Apparently, they are using Cbc as well, and run in the same issue: https://community.wolfram.com/groups/-/m/t/967349 , see answer of Daniel Litchblau.

The issue is that the solution returned doesn't satisfy the constraints. I believe there are no solutions to the problem, but that is not returned by the program. 

The problem solved is binary-only. There are 2 constraints and 24 variables. 

My question is, therefore: am I doing something wrong? I guess some tests are implemented, but I don't know how to call them. 

I use CBC-2.10.5 on VS2019 and modified the code of sample5 (to avoid Read and Write), and injected it in the project cbcExamplesSample2->sample2. I join here the code: [sample5.zip](https://github.com/coin-or/Cbc/files/4947261/sample5.zip)

When changing the variable reduction (line 127) from 1.15 to 1.2 per example, the problem passes from feasible to non feasible, but the answer of the code is the same. 

Thanks for your answer and time!
Simon

**Comment by jjhforrest** [comment]
Line 171 should be

int starts[] = { 0, 24 , 48};

**Comment by sKamer73** [comment]
Nice! Thank you so much, I went far for an explanation but it was an easier one, I hope it didn't take you too much time! 

Bests,
Simon

**Comment by jjhforrest** [comment]
Simon,

Only took a few minutes - once I had managed to run any example Cbc 
program! Clp examples seem to work in old way, but I found it very 
difficult to get any Cbc ones to compile and link.

John Forrest
