### ISSUE TITLE
Is it guaranteed that the results in OSX and Windows are consistent？

### ISSUE THREAD

**Issue by QuentinLew** [coin-or/Cbc#322]
Im using pulp to solve a LP problem. 

>     status = prob.solve(lp.PULP_CBC_CMD(msg=1, maxSeconds = 30))
>     print(status,lp.LpStatus[status])

>     Welcome to the CBC MILP Solver 
>     Version: 2.9.0 
>     Build Date: Feb 12 2015 
>     command line - ***\pulp\solverdir\cbc\win\64\cbc.exe 5471beeffcb24893aa36ee014349deb5-pulp.mps sec 30 branch printingOptions all solution 5471beeffcb24893aa36ee014349deb5-pulp.sol (default strategy 1)

It seems the results in OSX and Windows are not consistent (Both end within 10 sec). 
But always consistent between different machines with same OS.

I found pulp call `\pulp\solverdir\cbc\win\64\cbc.exe` or `\pulp\solverdir\cbc\osx\64\cbc` in either OS, data and parameters are same (Data Im using is kind of confidential, I will try to put more detail on the page after desensitization if necessary).

So I wonder if the CBC solver leads to this situation.

**Comment by tkralphs** [comment]
What do you mean by consistent? Same solution? Same objective value? Same running time? It is expected that any computational code will run differently on different machines (even machines with the same OS). In the case of an MILP solver, any slight difference in breaking a tie can lead to major differences in the path the algorithm takes. The end result (in terms of objective value) should be roughly the same, but floating point computations are not exact and there can be differences in cases where the input problem is ill-conditioned and the solver runs into numerical problems. We would need to know more to know if this is an expected difference or possibly a bug (note that you are using a very old release of Cbc).

**Comment by QuentinLew** [comment]
> 
> 
> What do you mean by consistent? Same solution? Same objective value? Same running time? It is expected that any computational code will run differently on different machines (even machines with the same OS). In the case of an MILP solver, any slight difference in breaking a tie can lead to major differences in the path the algorithm takes. The end result (in terms of objective value) should be roughly the same, but floating point computations are not exact and there can be differences in cases where the input problem is ill-conditioned and the solver runs into numerical problems. We would need to know more to know if this is an expected difference or possibly a bug (note that you are using a very old release of Cbc).

Thanks.  The old version was default when I install pulp. 
Can I use any parameter like a `randomSeed` to get reproducible results In different environments？

**Comment by tkralphs** [comment]
I'm not sure what you mean by "reproducible results." In general, you can expect the same objective value when solving the same instance on different machines (within some tolerance), but other than that, no. There is no way to guarantee identical runs on different machines. There do exist solvers that guarantee this (I believe XPress does, for example), but it is not easy to achieve.

**Comment by QuentinLew** [comment]
But as far as I know. 
If we have same random seed and same generator, then the algorithm always takes the same path?

**Comment by tkralphs** [comment]
Nope, when floating point computations are involved, all bets are off. The C++ standard is not very specific about how floating point computations must be implemented and there are subtle differences in compilers and hardware that make it difficult to ensure computations can be replicated without going to great lengths. If there are no floating point computations, it's easier to ensure replicability, but you still need to be careful not to break ties arbitrarily and other such things. If your code is parallel, then you have even bigger challenges in enforcing determinism (not sure if you're running Cbc in parallel). 

There is a ton of stuff written about this on, e.g., Stackoverflow, if you do some [Googling](https://www.google.com/search?q=differences+in+floating+computations+on+different+machines+site:stackoverflow.com). [This paper](https://www.appinf.com/download/FPIssues.pdf) and [this article](https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html) also have good introductions.

**Comment by QuentinLew** [comment]
Thank you. Closing the issue.
