### ISSUE TITLE
Interpreting the -thread argument to cbc is buggy

### ISSUE THREAD

**Issue by SnarkBoojum** [coin-or/Cbc#328]
The bug was reported long ago in Debian, see [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=598061) ; but since I took over the maintenance of the package, I'm trying to solve it.

It looks like a trivial issue with argument parsing : if you run "cbc -thread 2 problem.mps", then you get an error because the filename is interpreted as a command ; but if you run "cbc problem.mps -thread 2", things proceed normally.

I can confirm it's still there in version 2.10.5, so it's an old issue, but it's still biting.

**Comment by jjhforrest** [comment]
It is a feature - not a bug (and it is not just -thread).

The standard syntax is a sequence of commands (and argument if command 
takes one).  One exception was made for convenience and that is that if 
the first command is not on the list, then it will be interpreted as a 
possible input file and a notional -import will be assumed.

If you don't wish to use this short cut, then always use -import as -

cbc -thread 2 -import problem.mps -solve

John Forrest

**Comment by SnarkBoojum** [comment]
Ok, I'm completing the manpage we have in Debian to make it clearer. Thanks!
