### ISSUE TITLE
Wrong result

### ISSUE THREAD

**Issue by icze** [coin-or/Cbc#333]
Hi,

seems to getting the wrong objective value (always 0 instead of about 0.19211) for the mps-file [small.txt](https://github.com/coin-or/Cbc/files/5188961/small.txt)
when calling with
```
cbc small.mps -log 2 -presolve off -solve
```
Has anybody an idea what I'm doing wrong?

Output:

```
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Jun 26 2019

command line - cbc small.mps -log 2 -presolve off -solve (default strategy 1)
At line 1 NAME (null)
At line 2 OBJSENSE
MAX found after OBJSENSE - Coin ignores
At line 4 ROWS
At line 11 COLUMNS
At line 74 RHS
At line 79 BOUNDS
At line 102 ENDATA
Problem (null) has 5 rows, 22 columns and 42 elements
Coin0008I (null) read with 0 errors
logLevel was changed from 1 to 2
Option for presolve changed from on to off
0  Obj 0 Dual inf 1.0399512e-06 (8) w.o. free dual inf (0)
0  Obj 0 Dual inf 1.0399512e-06 (8) w.o. free dual inf (0)
Optimal - objective value 0
Optimal objective 0 - 0 iterations time 0.002
Total time (CPU seconds):       0.01   (Wallclock seconds):       0.01
```

Is OBJSENSE MAX ignored? (enforcing it with -max does not help)

Thanks for your help!
Ingo

**Comment by jjhforrest** [comment]
Scaling problem.

Very small element values.  With -dualtolerance 1.0e-8 gets 0.19211699
(with 1.0e-7 it is 0.16355199 - which shows how sensitive to tolerances 
it is).

**Comment by icze** [comment]
Thanks for the answer.

Setting the dual tolerance to 1.0e-8 works.
As we optimising quite different problems I'm not keen on setting a stricter tolerance for performance reasons. 
Perhaps I introduce a small heuristic like: when the smallest element is less than 1.0e-5 then use a stricter tolerance.
Or have you a hint for this topic?

Another approach would be the scaling: I tried to enforce a scaling via the parameter -scaling.
But it seems to have no effects. Is it because of the small number of elements?

Another observation:
When I'm enriching the system with additional unnecessary constraints I get 0.19211699 even with the default dual tolerance.

**Comment by icze** [comment]
Ok, we are doing the scaling now by ourself. Do you have recommendations about the ranges of the constraint and objective coefficients, rhs and bounds, e.g 1e-3 and 1e+6?

**Comment by icze** [comment]
With the given range we are doing fine.
Thanks
