### ISSUE TITLE
Error while compiling Cbc on Visual Studio 2019

### ISSUE THREAD

**Issue by toluwalope-TWS** [coin-or/Cbc#343]
I followed the steps for building Cbc on visual studio. However there seems to be errors with some includes like CglOddWheel.hpp.

Also with Cbc_nFeatures(), an error is reported - a function declared 'dllimport' may not be defined.

**Comment by tkralphs** [comment]
You'll need to report the exact steps you followed and the exact errors if you want help with this. The latest commits in both master and stable/2.10 both build with Visual Studio 2019 on Appveyor, e.g., https://ci.appveyor.com/project/tkralphs/cbc-s1r7t/builds/35258147.

**Comment by toluwalope-TWS** [comment]
I basically followed the steps here [https://coin-or.github.io/user_introduction.html#building-with-visual-studio-in-msys2]

1. I configured the compiler and set the path by running **vcvarsall.bat** script
2. I run the **bash**
3. I moved to pre-created folder "coinbrew"
4. I get coinbrew with `wget https://raw.githubusercontent.com/coin-or/coinbrew/master/coinbrew`
5. Then `chmod u+x coinbrew`
6. Followed by running` ./coinbrew fetch Cbc@master`
7. Build with `./coinbrew build Cbc --enable-msvc --no-prompt --build=x86_64-w64-mingw32 --no-third-party`
8. Build completed successfully. See image "build-complete"
<img width="884" alt="build-complete" src="https://user-images.githubusercontent.com/72813673/96157723-f473f480-0f12-11eb-83cf-ece37d08d774.PNG">

I navigated to the MSVisualStudio folder within Cbc to open the solution in my MS Visual Studio. After building the solution in visual studio, I get the error as below
<img width="726" alt="error_msvs" src="https://user-images.githubusercontent.com/72813673/96157566-bf67a200-0f12-11eb-99c3-964408f5c236.PNG">

**Comment by tkralphs** [comment]
I'm a little unsure what your final goal is. The first step with `coinbrew` already built everything that the Visual Studio solution would build for you. Those are just two mechanisms for building the same set of artifacts. There is no need to even open the Visual Studio solution (which looks as though it's a bit broken anyway). Just look in the `dist` directory for the libraries, DLLs, headers, etc.

**Comment by toluwalope-TWS** [comment]
@tkralphs thanks for your comment. I actually decided to go to Bintray [https://bintray.com/coin-or/download/Cbc](https://bintray.com/coin-or/download/Cbc) to get the already compiled version for Cbc.

I have another question though.
Cbc has shared memory parallelism, which can be enabled with the `--enable-cbc-parallel` if I build with `coinbrew`. Is this already enable for the compiled Visual Studio version I get on Bintray ?

**Comment by tkralphs** [comment]
You can check the exact recipe used for various versions by looking at `appveyor.yml` in the root directory. Currently, `master` and `stable/2.10` are being built with `--enable-cbc-parallel`, but this is a recent change so most releases would not be. The next release, when it comes, will be.

**Comment by toluwalope-TWS** [comment]
Thanks for the info. I am working with `stable/2.10` which should work then with `--enable-cbc-parallel`
