### ISSUE TITLE
"It can be called trough..." rust-lp-modeler too!

### ISSUE THREAD

**Issue by carrascomj** [coin-or/Cbc#355]
Hello,

[rust-lp-modeler](https://github.com/jcavat/rust-lp-modeler) supports calling Cbc trough the rust bindings for the C API (https://github.com/KardinalAI/coin_cbc) or, alternatively, using the CLI.

**Comment by lovasoa** [comment]
And from [good_lp](https://github.com/rust-or/good_lp) too :)

**Comment by tkralphs** [comment]
Fixed via cd374a172d888b27e1995fb96f252b49a2126b09
