### ISSUE TITLE
cbc vs. cplex, small result discrepancy

### ISSUE THREAD

**Issue by christoph-cullmann** [coin-or/Cbc#356]
With a simple solver driver like (simplified a bit):

```
    std::unique_ptr<OsiClpSolverInterface> solver1(new OsiClpSolverInterface());
    if (solver1->readLp(infile)) {
        return false;
    }

    CbcModel model(*solver1.get());
    solver1.reset();

    CbcSolverUsefulData cbcData;

    CbcMain0(model, cbcData);

    std::vector<const char *> args {"clpsolve", "-solve", "-quit", nullptr};
    CbcMain1(args.size() - 1, args.data(), model, cbcData);
```

the attached ilp computes a result of 24093347 compared to cplex 24093348 on Linux 64 bit (compiled with clang).

Perhaps somebody has an idea what is handled wrong here, I see no obvious issue in the driver code.
[value_24093348.lp.gz](https://github.com/coin-or/Cbc/files/5857101/value_24093348.lp.gz)

**Comment by christoph-cullmann** [comment]
A similar effect is visible with this attached ilp, just there you have differences only on Windows 64 (compared to cplex or cbc Linux runs): 
6691793926 vs. 1675079688

[value_6691793926.lp.gz](https://github.com/coin-or/Cbc/files/5857120/value_6691793926.lp.gz)

**Comment by h-g-s** [comment]
Hi,

 

Both CPLEX and CBC use tolerances to determine if the solution is optimal or not. As your objective function has larger numbers and the relative difference between both is small this is expected. Please check absolute and relative gap parameters.

**Comment by christoph-cullmann** [comment]
Hmm, you are right, for CPLEX we use

CPXsetdblparam(env, CPX_PARAM_EPGAP, 1e-9);

But for CBC we set nothing and use the default value.

Just to be sure: This is in CBC terms the CbcAllowableFractionGap double parameter?

I tried to pass the same value to that one to the above CbcModel, that didn't really affect the result.

**Comment by christoph-cullmann** [comment]
Hmm, 

model.setDblParam(CbcModel::CbcIntegerTolerance, 1e-10);

does the job for me, at least for the 24093348 variant, will test the other one again, too.

Thanks already for the hint & very quick response!

**Comment by christoph-cullmann** [comment]
Ok, I solved my issues by modifying some solving parameters, thanks for the feedback.
I still have some issues with termination Linux vs. Windows for value_24093348.lp.gz, but I guess I will need to experiment more with that myself.
