### ISSUE TITLE
CbcModel wrongly concludes Optimal when time limit hit

### ISSUE THREAD

**Issue by jhmgoossens** [coin-or/Cbc#364]
Hi,
I'm using MIPLIBs mas74 to test CbcSolver with a small time limit for Seconds not Improved (secni 5). The search stops as expected, but isProvenOptimal is wrongly reported as true.

It goes something like this:
1. Several non-optimal solutions are found, 
2. Then the search is stopped "Cbc0020I Exiting on maximum time" (all OK so far), but lastly 
3. The CbcModel reports Search completed and isProvenOptimal = true, even though there is a large gap left. 

The reason seems to be that a call to saveBestSolution (from CbcModel.cpp:4827) is made _after_ the search is stopped (2.), causing lastTimeImprovingFeasSol_ to be set to current time, and then the final steps of the branchAndBound concludes wrongly that the time limit must not have been hit.

How to fix this? Of course I can double check the best obj value with best possible obj value, but that's just a workaround.

The log looks like this:

```
[...]
Cbc0010I After 503 nodes, 252 on tree, 12310.694 best solution, best possible 10593.336 (6.74 seconds)
**Cbc0020I Exiting on maximum time
Cbc0005I Partial search - best objective 12310.694 (best possible 10593.336), took 132049 iterations and 28059 nodes (9.26 seconds)
Cbc0032I Strong branching done 5020 times (28511 iterations), fathomed 0 nodes and fixed 1 variables
Cbc0041I Maximum depth 23, 1211 variables fixed on reduced cost (complete fathoming 6 times, 27554 nodes taking 128396 iterations)
Cbc0038I Probing was tried 11 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.019 seconds)
[…]
Cbc0038I Stored from first was tried 510 times and created 21 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Cbc0012I Integer solution of 12310.694 found by Reduced search after 133006 iterations and 28109 nodes (9.28 seconds)

[here another call is made to maximumSecondsReached, but this time hitMaxTime = false is returned!]

**Cbc0001I Search completed - best objective 12310.6943606, took 133006 iterations and 28109 nodes (9.28 seconds)
Cbc0032I Strong branching done 510 times (3254 iterations), fathomed 0 nodes and fixed 0 variables
Cbc0035I Maximum depth 12, 236 variables fixed on reduced cost
Total time (CPU seconds):       9.30   (Wallclock seconds):       9.30
```

Using a different value for secni _does_ produce the expected behavior, for example secni 4 gives:
``` 
[…]
Cbc0038I Full problem 13 rows 111 columns, reduced to 13 rows 22 columns
**Cbc0020I Exiting on maximum time
Cbc0005I Partial search - best objective 12323.694 (best possible 10593.336), took 84839 iterations and 16737 nodes (7.71 seconds)
Cbc0032I Strong branching done 5060 times (28706 iterations), fathomed 1 nodes and fixed 8 variables
Cbc0041I Maximum depth 24, 1212 variables fixed on reduced cost (complete fathoming 2 times, 16236 nodes taking 81194 iterations)
Cbc0038I Probing was tried 11 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.025 seconds)
[…]
Cbc0038I Stored from first was tried 510 times and created 21 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
**Cbc0020I Exiting on maximum time
**Cbc0005I Partial search - best objective 12323.694 (best possible 10593.326), took 85796 iterations and 16787 nodes (7.76 seconds)
Cbc0032I Strong branching done 510 times (3254 iterations), fathomed 0 nodes and fixed 0 variables
Cbc0035I Maximum depth 12, 236 variables fixed on reduced cost
Total time (CPU seconds):       7.81   (Wallclock seconds):       7.81
```

Any suggestions?

**Comment by jjhforrest** [comment]
Will look at it.

It is something to do with reduced search i.e. after some nodes the code 
decides it can do better by preprocessing the problem again using the 
best solution found so far.  It then does branch and bound again - so 
you get CbcModel::branchAndBound calling branchAndBound.  somehow the 
max time flag is getting lost on return.

John Forrest

**Comment by jjhforrest** [comment]
Should be fixed in master.

**Comment by jhmgoossens** [comment]
Confirmed fixed! Many thanks! 
It took you less time to fix it than for me to write the Issue :-)
