### ISSUE TITLE
Visual Studio 2019 CBC solution won't build due to cbcCInterfaceDLL project errors

### ISSUE THREAD

**Issue by jhmgoossens** [coin-or/Cbc#373]
I'm trying to get the CBC solution for VS2019 to build--even if building using coinbrew is advised.
Nearly all projects in the solution build in all configurations and platforms, except cbcCInterfaceDLL.
How can the Preprocessor definitions be changed to build successfully?

ThecbcCInterfaceDLL VS project, as I understand it, is trying to build a DLL with (only) the Cbc_C_Interface functionality dllexported while all dependencies are linked in as static libs. Currently the cbcCInterfaceDLL project doesn't build due to a compiler error: in Debug / x64:  Cbc_nFeatures': definition of _dllimport_ function not allowed
Note the _dllimport_, caused by missing CBCSOLVERLIB_BUILD. But after that is fixed, many more errors and warnings pop up.
For one with DLL_EXPORT defined in settings, this results in all includes trying to dllexport themselves and so resulting in Warnings LNK4217 since these functions are statically included in libs--so dllimport is conflicting.

Can the issues with cbcCInterfaceDLL project in the VS solution be fixed by other preprocessor definitions?
Thanks for your help.

BTW, I believe this issue _doesn't_ occur in the coinbrew build because it is not building in the same setup with only cbc_c_interface functionality exported.

**Comment by svigerske** [comment]
No, either you export all functions of libCbcSolver, or none, but there is nothing to export only the functions of the C interface.
To achieve this, one would have to ensure that `CBCSOLVERLIB_EXPORT` is defined to be `__declspec(dllexport)` for functions in `Cbc_C_Interface.h/c` only.

But I suggest to just delete `cbcCInterfaceDLL`.
