### ISSUE TITLE
problem with build using MS Visual Studio

### ISSUE THREAD

**Issue by jestspocko** [coin-or/Cbc#382]
I tried to build the solution following the instruction. The project did not built out of the box. Can you please instruct me how to fix the errors?

```
C:\Users\aewer\source\repos\CoinUtils\MSVisualStudio\v16\libCoinUtils\libCoinUtils.vcxproj : error  : The project file could not be loaded. Could not find a part of the path 'C:\Users\aewer\source\repos\CoinUtils\MSVisualStudio\v16\libCoinUtils\libCoinUtils.vcxproj'.  C:\Users\aewer\source\repos\CoinUtils\MSVisualStudio\v16\libCoinUtils\libCoinUtils.vcxproj

C:\Users\aewer\source\repos\Clp\MSVisualStudio\v16\libClp\libClp.vcxproj : error  : The project file could not be loaded. Could not find a part of the path 'C:\Users\aewer\source\repos\Clp\MSVisualStudio\v16\libClp\libClp.vcxproj'.  C:\Users\aewer\source\repos\Clp\MSVisualStudio\v16\libClp\libClp.vcxproj
 
.... (5 more )

```
I am sorry if this is too trivial. Only recently I have decided to give C++ a try in order to delve more into optimization topics.

I am on Windows x64, using Microsoft Visual Studio Community 2019 Version 16.9.2

**Comment by kotori2** [comment]
Clone all dependencies [described here](https://github.com/coin-or/Cbc/blob/master/.coin-or/config.yml) into one folder
![image](https://user-images.githubusercontent.com/17663689/130910772-ceac2fce-9c0b-48c0-b450-cdd139d6b5bb.png)
