### ISSUE TITLE
Can't download any binary from Bintray

### ISSUE THREAD

**Issue by Vitorbnc** [coin-or/Cbc#390]
Hello!

I am unable to download anything from [bintray](https://bintray.com/package/files/coin-or/download/Cbc?order=desc&sort=fileLastModified&basePath=&tab=files) (or [bintray](https://bintray.com/coin-or/download/Cbc#files/) ) it always gives the `Forbidden!` error.
Is there a mirror available?

**Comment by tkralphs** [comment]
Unfortunately, bintray will shut down on May 1 and today was a brown-out to make sure everyone is aware that the change is coming. Everything will probably be back to normal later today or tomorrow (actually, I can now see the list of files available for download at the first link), but in the meantime, we are making plans to move to another service. 

There may be an interruption in the ability to download binaries starting May 1. One possibility is to download the existing binaries and move to an alternate host before then. I would certainly be happy to have volunteers to help with that.

**Comment by Vitorbnc** [comment]
Thanks! They are indeed working now. 
I could try to batch download the binaries. Have you chosen a new server already ?

**Comment by Vitorbnc** [comment]
By the way, what are the different msvc versions (ie -md, -mdd, -mtd, etc)?

**Comment by xmunoz** [comment]
My understanding is that we're trying to move to Github Releases, and host the binaries there.

**Comment by tkralphs** [comment]
The different binaries correspond to the different run-time libraries that Visual Studio supports. My understanding is a bit sketchy, but basically, these were built with the `\MD` \MT`, `\MDd`, and \MTd` flags, as described [here](https://docs.microsoft.com/en-us/cpp/build/reference/md-mt-ld-use-run-time-library?view=msvc-160).

As for batch downloading, that's probably a good idea. We can probably just put them where the binaries were hosted before bintray: https://www.coin-or.org/download/binary.

**Comment by tkralphs** [comment]
I've now mirrored the binaries here for the time being:

https://www.coin-or.org/download/binary/Cbc

but we are working on getting up and running with Github Actions.

**Comment by Vitorbnc** [comment]
That's great to know! 
I am going to close this issue as it has been solved. 
Thanks for the super quick support!

**Comment by xmunoz** [comment]
I think we should update the readme before calling this finished.

**Comment by tkralphs** [comment]
We also need to update READMEs for other projects in the Cbc stack, but I can do this using my automated script :). We could think about adding automatic generation of an updated README to Github Actions. What would eventually be nice is to have some additional automations that we currently need to do by hand as part of the release process in Github Actions as well, but this may not be the place to talk about that.

**Comment by xmunoz** [comment]
Have you already uploaded the binaries for all the other projects? If no, then I think we should merge my PR with the idea that we will overwrite it with automation soon. If yes, automate away!

**Comment by xmunoz** [comment]
Oh, sorry, I think I misunderstood. I guess Cbc is packaged with the other projects, so it would be the same link for all of them. Yes, by all means, feel free to close my PR.

**Comment by dget** [comment]
Hi @tkralphs - thank you for setting up the mirror! I noticed a few of the URLs (including https://www.coin-or.org/download/binary/Cbc/Cbc-2.9.9-linux-x86_64-gcc4.6.tgz) are returning 403 Forbidden errors. Is that something you could adjust?

**Comment by tkralphs** [comment]
@mjsaltzman Can you take a look at this? Permissions look OK, but the file ownership is different on these files, I guess that's the reason.

**Comment by mjsaltzman** [comment]
Try now.

**Comment by harto** [comment]
Seems to work now — thank you 🙏

**Comment by mjsaltzman** [comment]
Was an issue with SELinux contexts.
