### ISSUE TITLE
ratioGap question

### ISSUE THREAD

**Issue by EnsignDaniels** [coin-or/Cbc#423]
Hello,

I believe I need some explanation on the ratioGap parameter. When I'm trying to solve my problem, by setting ratioGap to 0.05 it means that when the gap between calculated solution and optimal is 5 percent of lower, Cbc should finish and return the value. However, the calculations aren't stopping even when gap is 1 percent. 

Can you please correct me if I'm wrong and shed some light on this?
[test8-1-1-1.txt](https://github.com/coin-or/Cbc/files/6754572/test8-1-1-1.txt)

**Comment by WanHaitao96** [comment]
According to your log, the current gap is 
(3227.346 - 2600.911) / 3227.346 = 0.194 = 19.4%
