### ISSUE TITLE
Cbc build error

### ISSUE THREAD

**Issue by opperud** [coin-or/Cbc#426]
Hey! 

Im trying to build cbc, and recieve the error that can be seen below. 

From https://github.com/coin-or/Cbc

##################################################
##################################################

libtool: link: `CbcHeuristic.lo' is not a valid libtool object
make[2]: *** [Makefile:848: libCbc.la] Error 1
make[1]: *** [Makefile:760: all] Error 2
make: *** [Makefile:607: all-recursive] Error 1

Build failed, see error output above

**Comment by tkralphs** [comment]
Without a little more information, it will be hard to guess at the problem. Please provide OS, compiler, how you obtained the source code, the exact sequence of commands, etc. Thanks!

**Comment by opperud** [comment]
Im trying to install DIP for python3 on windows 10.
Using WSL 2 as my linux compiler. 
Have followed the instructions in the install file over at https://github.com/coin-or/Dip/blob/master/INSTALL.md.
got the source code with 
      git clone https://www.github.com/coin-or/coinbrew
Then fetch the code DIP with:
       ./coinbrew fetch 
In the interactive suite I specified 15 (DIP). Did the same procedure for build for DIP, and when it is building its dependencies I ran into the issue 

From https://github.com/coin-or/Cbc

##################################################

Building Cbc 2.10
##################################################

libtool: link: `CbcHeuristic.lo' is not a valid libtool object
make[2]: *** [Makefile:848: libCbc.la] Error 1
make[1]: *** [Makefile:760: all] Error 2
make: *** [Makefile:607: all-recursive] Error 1

Build failed, see error output above


Thanks for the help!

**Comment by tkralphs** [comment]
How did you answer when coinbrew asked whether you wanted the latest release? I tried to replicate and was successful in building the latest release of Dip on WSL without any errors. However, from the output, you are not building a release, so I'm still not sure what you did exactly. With the latest release of Dip (`0.95.0`), you should have gotten the latest release of Cbc (`2.10.5`), but you have the latest stable branch `2.10`.

**Comment by opperud** [comment]
I asked for the latest release. It is working now, I decided to first getch and build the latest release of Cbc (2.10.5) and then fetch and build DIP (0.95.0). 

Thanks for your patient and help!
