### ISSUE TITLE
building from source via coinbrew exits with error code 1

### ISSUE THREAD

**Issue by maks-io** [coin-or/Cbc#443]
When i follow the instructions as listed in https://github.com/coin-or/Cbc#using-coinbrew to install from current master branch, the last of the 4 commands (`./coinbrew build Cbc`) exits with error code 1, but no further information about what went wrong.
You can check out my attached error log.

To make sure it's not my machine and/or operating system I tested it on 3 different machines, one of them with Debian 10, the others with Fedora 34. Same problem on all of them.

Anybody ran into similar problems?

[error.txt](https://github.com/coin-or/Cbc/files/7205572/error.txt)

**Comment by tkralphs** [comment]
Hmm, I'm a little confused. You said that you got no further information about what went wrong, but the log you attached shows the output of configure and there is a clear error message there. It says you don't have a C compiler installed. `gcc` typically does come installed by default in Linux distros, so I don't quite know what's going on. There is also the error message
```
make: command not found
```
in the output. Something is strange about your setup. You either have a some minimal install without `make` and `gcc` or your `PATH` was corrupted somehow. You definitely need some compiler toolchain installed.
