### ISSUE TITLE
CBC Warm Start not behaving appropriately?

### ISSUE THREAD

**Issue by rwoodama** [coin-or/Cbc#446]
Our team has developed a very large LP (~3M var) that we solve with CBC and PuLP.  

We are generally happy with the current solution times (~25m on a regular laptop) but we are investigating warm starting to see if we can get performance improvements.

I have built a toy version (~600 var) of our problem built that generates synthetic data (controlling with random seed) where I repeatedly solve the same problem with and without mip start.  That didn't seem to make a difference.

So then I thought - maybe its because MIP start is intended for MIPs, So I then have the same code also solve the same problem with all the variables integer too.  Again no difference.

The code is attached.  It makes its own data and thereafter tries to read back in the previous solution.  Theoretically, the previous solution is optimal and so it should not have to search for long if at all.

From looking at the log, it reads the MIP file but then ignores it and proceeds with the exact same solve sequence as if it didn't read the mip file.

I readily recognize that I may just not know what I am doing!
Thanks
[WarmStartTestCode.txt](https://github.com/coin-or/Cbc/files/7297272/WarmStartTestCode.txt)

**Comment by jjhforrest** [comment]
If I put out a .lp file and save the solution from stand alone cbc then
mipstart does get a solution.  An older version hiccups a bit.  But if you
have a model with continuous variables, I do not think hot start would
really help.  If you were using standalone cbc then basisin and basisout
are what you would want.  I do not see those as available in pulp.  Looking
at the documentation for pulp, I don't see an easy way to do what you want
- but I will think about it a bit.

John Forrest

**Comment by rwoodama** [comment]
Thanks John.  I will dig into saving the .lp file before concluding my exploration.

________________________________

**Comment by jjhforrest** [comment]
I know very little about pulp and python, so I can not come up with an
elegant solution - but if you are dealing with continuous problems then the
following changes  - basisin/basisout to coin_api.py work
        cmds += "basisin /tmp/lp.bas "
        for option in options:
            cmds += option + " "
        if self.mip:
            cmds += "branch "
        else:
            cmds += "initialSolve "
        cmds += "basisout /tmp/lp.bas "

The first time lp.bas should not exist (or could just be an empty basis)

Adding these commands should be on options - but I don't know enough about
pulp/python to do that.

**Comment by rwoodama** [comment]
Thanks John.  I found out on the pulp git site, that you need to set keepFiles = True for the warm start to take.
But it really appears to be (as you mentioned above) that this something the branch and bound code would use (cbc).  CLP is the LP solver so I need to investigate the basis in and out for my continuous optimization problem.
Cheers

**Comment by tkralphs** [comment]
Looks like this is resolved, so I'm closing it. Feel free to re-open if needed.
