### ISSUE TITLE
Getting dual/Marginal values from CBC in the CLI

### ISSUE THREAD

**Issue by vignesh1987** [coin-or/Cbc#450]
Hi, 
I would like to know if there is a simple way to get the dual values from an LP problem by using CBC in a command-line interface. 
I use the following for getting the optimal solution.
`cbc <abc.lp> solve solu <abc_sol.txt>`

**Comment by jjhforrest** [comment]
Add

-printing all

duals are last column in output

**Comment by vignesh1987** [comment]
Thanks John. "-printing all" now prints the entire solution.
