### ISSUE TITLE
ILP solving 4400 via cbc vs. 4401 via cplex

### ISSUE THREAD

**Issue by christoph-cullmann** [coin-or/Cbc#451]
Using current master branch of clp/cbc/.... for the attached ILP the CBC solver will round one down.

`Welcome to the CBC MILP Solver 
Version: Trunk (unstable) 
Build Date: Nov  9 2021 

command line - ../usr/bin/cbc test/value_4401.lp (default strategy 1)
 CoinLpIO::readLp(): Maximization problem reformulated as minimization
Coin0009I Switching back to maximization to get correct duals etc
Continuous objective value is 4408.5 - 0.00 seconds
Cgl0003I 4 fixed, 0 tightened bounds, 16 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 0 tightened bounds, 10 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 0 tightened bounds, 6 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 0 tightened bounds, 4 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 0 tightened bounds, 1 strengthened rows, 0 substitutions
Cgl0004I processed model has 57 rows, 79 columns (79 integer (47 of which binary)) and 317 elements
Coin3009W Conflict graph built in 0.000 seconds, density: 1.879%
Cgl0015I Clique Strengthening extended 0 cliques, 0 were dominated
Cutoff increment increased from 0.0001 to 0.9999
Cbc0038I Initial state - 8 integers unsatisfied sum - 2
Cbc0038I Solution found of -4402.5
Cbc0038I Branch and bound needed to clear up 8 general integers
Cbc0038I Full problem 57 rows 79 columns, reduced to 14 rows 28 columns
Cbc0038I Cleaned solution of -4400
Cbc0038I Before mini branch and bound, 71 integers at bound fixed and 0 continuous of which 6 were internal integer and 0 internal continuous
Cbc0038I Mini branch and bound did not improve solution (0.01 seconds)
Cbc0038I Round again with cutoff of -4401.05
Cbc0038I Reduced cost fixing fixed 27 variables on major pass 2
Cbc0038I Solution found of -4402.5
Cbc0038I Branch and bound needed to clear up 8 general integers
Cbc0038I Full problem 58 rows 79 columns, reduced to 15 rows 24 columns
Cbc0038I Mini branch and bound could not fix general integers
Cbc0038I No solution found this major pass
Cbc0038I Before mini branch and bound, 71 integers at bound fixed and 0 continuous of which 6 were internal integer and 0 internal continuous
Cbc0038I Mini branch and bound did not improve solution (0.01 seconds)
Cbc0038I After 0.01 seconds - Feasibility pump exiting with objective of -4400 - took 0.01 seconds
Cbc0012I Integer solution of -4400 found by feasibility pump after 0 iterations and 0 nodes (0.01 seconds)
Cbc0031I 2 added rows had average density of 6.5
Cbc0013I At root node, 9 cuts changed objective from -4401.5 to -4400 in 1 passes
Cbc0014I Cut generator 0 (Probing) - 0 row cuts average 0.0 elements, 1 column cuts (1 active)  in 0.000 seconds - new frequency is 1
Cbc0014I Cut generator 1 (Gomory) - 1 row cuts average 5.0 elements, 0 column cuts (0 active)  in 0.000 seconds - new frequency is 1
Cbc0014I Cut generator 2 (Knapsack) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.000 seconds - new frequency is -100
Cbc0014I Cut generator 3 (Clique) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.000 seconds - new frequency is -100
Cbc0014I Cut generator 4 (OddWheel) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.000 seconds - new frequency is -100
Cbc0014I Cut generator 5 (MixedIntegerRounding2) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.000 seconds - new frequency is -100
Cbc0014I Cut generator 6 (FlowCover) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.000 seconds - new frequency is -100
Cbc0014I Cut generator 7 (TwoMirCuts) - 8 row cuts average 6.9 elements, 0 column cuts (0 active)  in 0.000 seconds - new frequency is -100
Cbc0001I Search completed - best objective -4400, took 0 iterations and 0 nodes (0.02 seconds)
Cbc0035I Maximum depth 0, 21 variables fixed on reduced cost
Cuts at root node changed objective from -4401.5 to -4400
Probing was tried 1 times and created 1 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 1 times and created 1 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 1 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 1 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
OddWheel was tried 1 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 1 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 1 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 1 times and created 8 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 1 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Cgl0014I Postprocessing changed objective from 4399 to 4400 - possible tolerance issue - try without preprocessing

Result - Optimal solution found

Objective value:                4400.00000000
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.02
Time (Wallclock seconds):       0.02

Total time (CPU seconds):       0.02   (Wallclock seconds):       0.02

`

[value_4401.lp.txt](https://github.com/coin-or/Cbc/files/7505685/value_4401.lp.txt)

**Comment by christoph-cullmann** [comment]
Disabling presolving naturally solves this, like hinted at end of output.

**Comment by jjhforrest** [comment]
Christoph,

Try updating master and running it again.  my current master cbc gives 4401.

For some hours there was a bad bug in master simplex due to some 
changes.  It did not show up initially on my tests as it was an 
uninitialized variable which was zero in my builds.

John Forrest

**Comment by christoph-cullmann** [comment]
You are right ;=) I exactly caught that revision :/

Thanks a lot for the hint...
Works now here, too.
