### ISSUE TITLE
Warning: No available formula with the name "gcc" (dependency of coin-or-tools/coinor/cbc)

### ISSUE THREAD

**Issue by mosa11am** [coin-or/Cbc#458]
I wanted to download Cbc solver for python. I updated my macbook to download Xcode. I downloaded the latest version of homebrew and followed the instructions in the following link.

https://github.com/coin-or/Cbc

brew tap coin-or-tools/coinor

brew install coin-or-tools/coinor/cbc

however i got stuck here and received that error

Warning: No available formula with the name "gcc" (dependency of coin-or-tools/coinor/cb

**Comment by tkralphs** [comment]
I guess maybe the generic `gcc` recipe is no longer available in homebrew. It should now probably be something like `gcc9`. But in the  meantime, Cbc was added to homebrew core, so just plain `brew install cbc` should work.

**Comment by tkralphs** [comment]
Closing this in favor of https://github.com/coin-or-tools/homebrew-coinor/issues/72.
