### ISSUE TITLE
Bug Report - CglProbing::probe Method

### ISSUE THREAD

**Issue by danilosouzaa** [coin-or/Cbc#479]
Hi,
I'm having problems running CBC for the following instances:
[supportcase17.mps.gz](https://github.com/coin-or/Cbc/files/7964889/supportcase17.mps.gz)
[supportcase33.mps.gz](https://github.com/coin-or/Cbc/files/7964890/supportcase33.mps.gz)
[stp3d.mps.gz](https://github.com/coin-or/Cbc/files/7964883/stp3d.mps.gz)
[academictimetablesmall.mps.gz](https://github.com/coin-or/Cbc/files/7964818/academictimetablesmall.mps.gz)
[air04.mps.gz](https://github.com/coin-or/Cbc/files/7964819/air04.mps.gz)
[bley_xl1.mps.gz](https://github.com/coin-or/Cbc/files/7964820/bley_xl1.mps.gz)
[cryptanalysiskb128n5obj16.mps.gz](https://github.com/coin-or/Cbc/files/7964822/cryptanalysiskb128n5obj16.mps.gz)
[dcmst_v20a50d4.mps.gz](https://github.com/coin-or/Cbc/files/7964825/dcmst_v20a50d4.mps.gz)
[ex10.mps.gz](https://github.com/coin-or/Cbc/files/7964826/ex10.mps.gz)
[gfd-schedulen180f7d50m30k18.mps.gz](https://github.com/coin-or/Cbc/files/7964831/gfd-schedulen180f7d50m30k18.mps.gz)
[hanoi5.mps.gz](https://github.com/coin-or/Cbc/files/7964836/hanoi5.mps.gz)
[l2p12.mps.gz](https://github.com/coin-or/Cbc/files/7964837/l2p12.mps.gz)
[momentum1.mps.gz](https://github.com/coin-or/Cbc/files/7964838/momentum1.mps.gz)
[momentum3.mps.gz](https://github.com/coin-or/Cbc/files/7964840/momentum3.mps.gz)
[mzzv11.mps.gz](https://github.com/coin-or/Cbc/files/7964846/mzzv11.mps.gz)
[neos8.mps.gz](https://github.com/coin-or/Cbc/files/7964847/neos8.mps.gz)
[neos10.mps.gz](https://github.com/coin-or/Cbc/files/7964849/neos10.mps.gz)
[neos-934531.mps.gz](https://github.com/coin-or/Cbc/files/7964850/neos-934531.mps.gz)
[neos-3083819-nubu.mps.gz](https://github.com/coin-or/Cbc/files/7964851/neos-3083819-nubu.mps.gz)
[neos-3214367-sovi.mps.gz](https://github.com/coin-or/Cbc/files/7964852/neos-3214367-sovi.mps.gz)
[neos-3696678-lyvia.mps.gz](https://github.com/coin-or/Cbc/files/7964853/neos-3696678-lyvia.mps.gz)
[neos-4306827-ravan.mps.gz](https://github.com/coin-or/Cbc/files/7964854/neos-4306827-ravan.mps.gz)
[neos-4724674-aorere.mps.gz](https://github.com/coin-or/Cbc/files/7964855/neos-4724674-aorere.mps.gz)
[neos-4738912-atrato.mps.gz](https://github.com/coin-or/Cbc/files/7964856/neos-4738912-atrato.mps.gz)
[ns903616.mps.gz](https://github.com/coin-or/Cbc/files/7964857/ns903616.mps.gz)
[pb-simp-nonunif.mps.gz](https://github.com/coin-or/Cbc/files/7964859/pb-simp-nonunif.mps.gz)
[radiationm18-12-05.mps.gz](https://github.com/coin-or/Cbc/files/7964870/radiationm18-12-05.mps.gz)
[radiationm40-10-02.mps.gz](https://github.com/coin-or/Cbc/files/7964871/radiationm40-10-02.mps.gz)
[routing_0016.mps.gz](https://github.com/coin-or/Cbc/files/7964881/routing_0016.mps.gz)
[shs1014.mps.gz](https://github.com/coin-or/Cbc/files/7964882/shs1014.mps.gz)
[piperout-27.mps.gz](https://github.com/coin-or/Cbc/files/7964973/piperout-27.mps.gz)

The error message displayed is similar to all:
cbc: ****/Cgl/src/CglProbing/CglProbing.cpp:5700: int CglProbing::probe(const OsiSolverInterface&, const OsiRowCutDebugger*, OsiCuts&, double*, double*, CoinPackedMatrix*, CoinPackedMatrix*, const CoinBigIndex*, const int*, const double*, const double*, const char*, double*, double*, int*, CglTreeInfo*): Assertion `newLo[icol]==COIN_DBL_MAX' failed.

I got the version on repository Cbc@master (used command: coinbrew fetch Cbc@master).
To compile the following command was used:
export CXXFLAGS="-O0 -g3 -fPIC -fopenmp" ; export LDFLAGS="" ;  ./coinbrew build Cbc --no-prompt --prefix="/home/haroldo/danilo/versao2022/execTemp" --verbosity=4  --enable-debug --tests none --enable-shared --disable-static --enable-relocatable --parallel-jobs=3
Tests were performed out on the Operational Systems:
 - CentOS Linux release 7.9.2009
- Ubuntu 18.04.6 LTS
Comand line Used:
./cbc -import nameInstance.mps.gz -timeM elapsed -seconds 10800 -solve -quit

output erro:
[erro-academictimetablesmall.txt](https://github.com/coin-or/Cbc/files/7964942/erro-academictimetablesmall.txt)
[erro-air04.txt](https://github.com/coin-or/Cbc/files/7964943/erro-air04.txt)
[erro-bley_xl1.txt](https://github.com/coin-or/Cbc/files/7964944/erro-bley_xl1.txt)
[erro-cryptanalysiskb128n5obj16.txt](https://github.com/coin-or/Cbc/files/7964945/erro-cryptanalysiskb128n5obj16.txt)
[erro-dcmst_v20a50d4.txt](https://github.com/coin-or/Cbc/files/7964946/erro-dcmst_v20a50d4.txt)
[erro-ex10.txt](https://github.com/coin-or/Cbc/files/7964947/erro-ex10.txt)
[erro-gfd-schedulen180f7d50m30k18.txt](https://github.com/coin-or/Cbc/files/7964948/erro-gfd-schedulen180f7d50m30k18.txt)
[erro-hanoi5.txt](https://github.com/coin-or/Cbc/files/7964949/erro-hanoi5.txt)
[erro-l2p12.txt](https://github.com/coin-or/Cbc/files/7964950/erro-l2p12.txt)
[erro-momentum1.txt](https://github.com/coin-or/Cbc/files/7964951/erro-momentum1.txt)
[erro-momentum3.txt](https://github.com/coin-or/Cbc/files/7964952/erro-momentum3.txt)
[erro-mzzv11.txt](https://github.com/coin-or/Cbc/files/7964953/erro-mzzv11.txt)
[erro-neos8.txt](https://github.com/coin-or/Cbc/files/7964954/erro-neos8.txt)
[erro-neos10.txt](https://github.com/coin-or/Cbc/files/7964955/erro-neos10.txt)
[erro-neos-934531.txt](https://github.com/coin-or/Cbc/files/7964956/erro-neos-934531.txt)
[erro-neos-3083819-nubu.txt](https://github.com/coin-or/Cbc/files/7964957/erro-neos-3083819-nubu.txt)
[erro-neos-3214367-sovi.txt](https://github.com/coin-or/Cbc/files/7964958/erro-neos-3214367-sovi.txt)
[erro-neos-3696678-lyvia.txt](https://github.com/coin-or/Cbc/files/7964959/erro-neos-3696678-lyvia.txt)
[erro-neos-4306827-ravan.txt](https://github.com/coin-or/Cbc/files/7964960/erro-neos-4306827-ravan.txt)
[erro-neos-4724674-aorere.txt](https://github.com/coin-or/Cbc/files/7964961/erro-neos-4724674-aorere.txt)
[erro-neos-4738912-atrato.txt](https://github.com/coin-or/Cbc/files/7964962/erro-neos-4738912-atrato.txt)
[erro-ns903616.txt](https://github.com/coin-or/Cbc/files/7964963/erro-ns903616.txt)
[erro-pb-simp-nonunif.txt](https://github.com/coin-or/Cbc/files/7964964/erro-pb-simp-nonunif.txt)
[erro-piperout-27.txt](https://github.com/coin-or/Cbc/files/7964965/erro-piperout-27.txt)
[erro-radiationm18-12-05.txt](https://github.com/coin-or/Cbc/files/7964966/erro-radiationm18-12-05.txt)
[erro-radiationm40-10-02.txt](https://github.com/coin-or/Cbc/files/7964967/erro-radiationm40-10-02.txt)
[erro-routing_0016.txt](https://github.com/coin-or/Cbc/files/7964968/erro-routing_0016.txt)
[erro-shs1014.txt](https://github.com/coin-or/Cbc/files/7964969/erro-shs1014.txt)
[erro-stp3d.txt](https://github.com/coin-or/Cbc/files/7964970/erro-stp3d.txt)
[erro-supportcase17.txt](https://github.com/coin-or/Cbc/files/7964971/erro-supportcase17.txt)
[erro-supportcase33.txt](https://github.com/coin-or/Cbc/files/7964972/erro-supportcase33.txt)

**Comment by jjhforrest** [comment]
Thanks,

The new coding triggered by #define FIXED_BOTH_WAYS was only tested on 
larger problems in optimized mode.  The answer will be to take out 
FIXED_BOTH_WAYS now and investigate further.  Probably it may just be 
taking out assert.

**Comment by danilosouzaa** [comment]
Problem solved in the last update
