### ISSUE TITLE
Optimal solution does not match in some instances

### ISSUE THREAD

**Issue by danilosouzaa** [coin-or/Cbc#481]
Hi,
When performing experiments on some instances, the optimal solution does not match the value of the best known solution.
**Instance 1:** 
[dano3_5.mps.gz](https://github.com/coin-or/Cbc/files/8004947/dano3_5.mps.gz)
Optimal solution found - Objective value: 576.925057172695 (Master Version - output file: [out-dano3_5.txt](https://github.com/coin-or/Cbc/files/8004993/out-dano3_5.txt))
CBC Version 2.9.9: 576.9249159565585 (output file: [out-dano3_5-2.9.9.txt](https://github.com/coin-or/Cbc/files/8004996/out-dano3_5-2.9.9.txt) )
Miplib report: 576.924915956562 (https://miplib.zib.de/instance_details_dano3_5.html)
**Instance 2:** 
[rlp1.mps.gz](https://github.com/coin-or/Cbc/files/8005408/rlp1.mps.gz)
Optimal solution found - Objective value: 22 (Master Version - output file: [out-rlp1.txt](https://github.com/coin-or/Cbc/files/8005420/out-rlp1.txt))
Gurobi 9.5.0: 15  ([out-rlp1-gurobi.txt](https://github.com/coin-or/Cbc/files/8005440/out-rlp1-gurobi.txt))
Miplib report: 15 (https://miplib.zib.de/instance_details_rlp1.html)

**Instance 3 (LB found greater than bks with timeout of 10800 seconds:** 
[trdnc.mps.gz](https://github.com/coin-or/Cbc/files/8006233/trdnc.mps.gz)
LB: -6657870.7 (Master Version - output file: [out-trdnc.txt](https://github.com/coin-or/Cbc/files/8006241/out-trdnc.txt))
Gurobi 9.5.0 (BKS): -666232.4  ([out-trdnc-gurobi.txt](https://github.com/coin-or/Cbc/files/8006245/out-trdnc-gurobi.txt))

I got the version on repository Cbc@master (used command: coinbrew fetch Cbc@master).
To compile the following command was used:
export CXXFLAGS="-O0 -g3 -fPIC -fopenmp" ; export LDFLAGS="" ; ./coinbrew build Cbc --no-prompt --prefix="/home/haroldo/danilo/versao2022/execTemp" --verbosity=4 --enable-debug --tests none --enable-shared --disable-static --enable-relocatable --parallel-jobs=3
Tests were performed out on the Operational Systems:

CentOS Linux release 7.9.2009
Ubuntu 18.04.6 LTS
Comand line Used:
./cbc -import nameInstance.mps.gz -timeM elapsed -seconds 10800 -solve -quit

**Comment by jjhforrest** [comment]
On 04/02/2022 21:11, danilosouzaa wrote:
>
> Hi,
> When performing experiments on some instances, the optimal solution 
> does not match the value of the best known solution.
> *Instance 1:*
> dano3_5.mps.gz 
> <https://github.com/coin-or/Cbc/files/8004947/dano3_5.mps.gz>
> Optimal solution found - Objective value: 576.925057172695 (Master 
> Version - output file: out-dano3_5.txt 
> <https://github.com/coin-or/Cbc/files/8004993/out-dano3_5.txt>)
> CBC Version 2.9.9: 576.9249159565585 (output file: 
> out-dano3_5-2.9.9.txt 
> <https://github.com/coin-or/Cbc/files/8004996/out-dano3_5-2.9.9.txt> )
> Miplib report: 576.924915956562 
> (https://miplib.zib.de/instance_details_dano3_5.html)
>
This may be a formatting issue.  Modern coders thought that printf 
should be replaced by std::cout (who am I to disagree).  So at end of 
search before postprocessing the solution was reported as above and 
after as 576.925 with no extra digits.  A few days ago I went back to 
printf for that important final value and on my run it was 576.924920911 
which is less than 1.0e-5 (cutoff increment) above Miplib report

> *Instance 2:*
> rlp1.mps.gz <https://github.com/coin-or/Cbc/files/8005408/rlp1.mps.gz>
> Optimal solution found - Objective value: 22 (Master Version - output 
> file: out-rlp1.txt 
> <https://github.com/coin-or/Cbc/files/8005420/out-rlp1.txt>)
> Gurobi 9.5.0: 15 (out-rlp1-gurobi.txt 
> <https://github.com/coin-or/Cbc/files/8005440/out-rlp1-gurobi.txt>)
> Miplib report: 15 (https://miplib.zib.de/instance_details_rlp1.html)
>
To do with over aggressive modifications to CglProbing - not same as 
#479 but probably related.  Will look further.


> *Instance 3 (LB found greater than bks with timeout of 10800 seconds:*
> trdnc.mps.gz <https://github.com/coin-or/Cbc/files/8006233/trdnc.mps.gz>
> LB: -6657870.7 (Master Version - output file: out-trdnc.txt 
> <https://github.com/coin-or/Cbc/files/8006241/out-trdnc.txt>)
> Gurobi 9.5.0 (BKS): -666232.4 (out-trdnc-gurobi.txt 
> <https://github.com/coin-or/Cbc/files/8006245/out-trdnc-gurobi.txt>)
>
Could be same as above

**Comment by jjhforrest** [comment]
I have updated master.  Result for instance 3 is interesting as I had 
not realized that default optimality tolerance for Gurobi is 1.0e-4 
which seems quite high. So Gurobi reported optimal value of -6662324 
with gap of 0.0064% and best possible of -6662751.  Cbc reports optimal 
value of -6662665.

**Comment by danilosouzaa** [comment]
Problem solved in the last update
