### ISSUE TITLE
Multiple documentation issues

### ISSUE THREAD

**Issue by albert-github** [coin-or/Cbc#496]
In the readme we see in respect to the pre-compiled doxygen documentation:

![image](https://user-images.githubusercontent.com/5223533/166106660-51450199-03fb-4243-9c51-f7af4cd608e9.png)

Where:
- the word `here` links to documentation of the Cbc 2.10.5 version generated with doxygen 1.8.13 on Thursday, July 16, 2020
- `Doxygen generated documentation` links to documentation of the Cbc 2.10.5 version generated with doxygen 1.8.5 on Monday, March 9, 2020
- `Doxygen-generated html documentation` links to documentation of the Cbc 2.10.5 version generated with doxygen 1.8.13 on Thursday, July 16, 2020

I think it would be good that the links point to the documentation:
- of the current Cbc version 2.10.7
- would all be generated with the same doxygen version, preferably the current doxygen 1.9.3 version.

Furthermore:
the `Cbc command-line guide` is specified as `https://projects.coin-or.org/CoinBinary/export/1059/OptimizationSuite/trunk/Installer/files/doc/cbcCommandLine.pdf` and redirects to https://github.com/coin-or/CoinBinary/export/1059/OptimizationSuite/trunk/Installer/files/doc/cbcCommandLine.pdf but this file does not exist, this should be corrected

**Comment by tkralphs** [comment]
Thanks for the report. These should all be fixed now.

**Comment by albert-github** [comment]
Looks all much better, unfortunately the used doxygen version is a bit older, 1.8.17 from December 27, 2019 whilst the current version is 1.9.3  from December 31, 2021.

**Comment by tkralphs** [comment]
> unfortunately the used doxygen version is a bit older, 1.8.17 from December 27, 2019 whilst the current version is 1.9.3 from December 31, 2021.

Why is that a problem? This is the version available in my Linux distro. I see you are a doxygen developer, so maybe you are trying to get everyone off of old versions? Anyway, thanks for taking time out to open this issue.

**Comment by albert-github** [comment]
@tkralphs Indeed I do quite a bit on doxygen, and yes when there is an update of the doxygen version used by a package and they didn't go to the latest version of doxygen I do advise them to do so as normally the standard versions distributed by the different *nix distributions lag a bit. It is not difficult to build to build a new doxygen version (see: https://www.doxygen.nl/download.html)
