### ISSUE TITLE
Documentation of Cbc command line options

### ISSUE THREAD

**Issue by kbrix2000** [coin-or/Cbc#510]
Dear Cbc developers,

where can I find the current documentation of the command line options of the Cbc executable?

What I found so far is the PDF document ["A Short Guide to the CBC Command Line Interface"](http://www.decom.ufop.br/haroldo/files/cbcCommandLine.pdf) by Haroldo Gambini Santos from 2017 that unfortunately seems to be a bit outdated. What I found out until now is that all command line options options (besides the model name to load) now start with a dash, e.g. "-solve" instead of "solve", otherwise they are ignored. Moreover, there is an option "-threads" to specify the number of threads to be used.

As its source the above PDF document quotes the Cbc online help which can be looked up from the Cbc prompt by typing "verbose 15" first and then typing a question mark, is this the reference document? Are all options listed in the Cbc online help?

Did the command line options change between versions 2.10.x and the current master branch?

Furthermore, from the [Cbc FAQ](https://coin-or.github.io/Cbc/faq.html) I learned that the order of the command line options matters.

Thanks a lot for your help!

**Comment by jhmgoossens** [comment]
Not sure about formal documentation, but AFAIK, the command line arguments are the same as the cbc prompt commands with added “-“ as you figured out. So run cbc and “use ? or ??? to see list of commands”. 
In this way, you can check available commands for the particular version you’re using.
Yes, the order of commands is important: _import_ before _solve_, etc.

**Comment by kbrix2000** [comment]
@jhmgoossens Thank you very much for your reply!
