### ISSUE TITLE
Model is not idempotent across MPS and LP files, which changes the optimum

### ISSUE THREAD

**Issue by natebragg** [coin-or/Cbc#518]
I have generated an [MPS file](https://github.com/coin-or/Cbc/files/9087820/ir.mps.gz) and an [LP file](https://github.com/coin-or/Cbc/files/9087828/ir.lp.txt) using the `Cbc_writeMps` and `Cbc_writeLp` API calls respectively, based off of a model that I have manually entered using the C API.

If I call `Cbc_printModel`, the output from the manually entered model and the reloaded MPS model are identical.  However, if I reload the LP file, the output of `Cbc_printModel` is quite different.  The optimums when I solve the MPS version and the LP version are also different.  It seems there is some issue with the LP output.

**Comment by tkralphs** [comment]
Could you say what exactly is the difference in the models? Are they different but equivalent, e.g., order of variables and constraints is different, or different and not equivalent? When you say the optimum is different, do you just mean a different solution and the same optimal value or a different optimal value? If it's a different solution, then this is expected and would be the case with any solver. Even very slightly different initial conditions can result in a different algorithm execution, though the optimal value should be the same. This short article explains how this is also the case for the commercial solver Gurobi.

https://support.gurobi.com/hc/en-us/articles/360013420131-What-are-the-differences-between-LP-and-MPS-file-formats-

Note that there may be differences in the precision of floating point numbers in the two cases.

**Comment by natebragg** [comment]
Different optimal values. MPS: -15297.45; LP: -14979.23333

The MPS value is the same as the result of that MPS file using CPLEX, Gurobi, and Scip.

This may also be a good time to mention that the MPS optimal value also doesn't agree with the optimal value from the model as input by the API, in spite of the two having identical output from `Cbc_printModel`.  That's what inspired me to try the LP format.

The difference in the MPS and LP models is not clear.  It may be as simple as order of variables and constraints, but I'm having trouble determining that since at a minimum the order is dramatically rearranged making it difficult to compare them.

**Comment by jjhforrest** [comment]
I am unable to reproduce error - when I run with latest stable, I get 
-15297.45 with both.

The two models seem to be identical.  I wrote a small program to sort 
the columns by name.

Have you tried with latest version? The model does have a lot of 9999999 's

**Comment by natebragg** [comment]
I'm on the latest release 2.10.8, and that's where I'm seeing this behavior.  I'm not sure I'm set up to install from master.  Are you able to reproduce on 2.10.8?  If so then this must have been fixed in the last two months.

**Comment by jjhforrest** [comment]
Unable to reproduce error on 2.10.8. Have built it various ways - but it 
has got -15297.45 from ir.lp each time.

**Comment by jjhforrest** [comment]
2.10.8 looks good - BUT I have managed to get problem on more recent 
code.  Will look into it.

**Comment by natebragg** [comment]
Just as a follow up, I tried using the `cbc` application to import my LP file, and the optimal value there was the same, so I realized there must be a difference in how I was using the API, and I discovered that it was the preprocessing step that changes the result.

In `cbc`, if you run:

    preprocess off
    import ir.lp
    solve

The optimum is the one I gave, -14979.23333.  Is this expected behavior, to have different values with and without preprocessing?

**Comment by jjhforrest** [comment]
The value should be the same.  It looks complicated and may take me some 
time to debug.  I think that in the end it will be some accuracy issue.

With preprocessing off the run using the .lp file decides that it is 
worth doing a bit of preprocessing after 500 nodes and restarting as 
problem is smaller.  For some reason (any slight perturbation will do 
e.g. order of variables different) the run using mps file does not 
restart.  So I have to find out what is wrong with the preprocessing 
after 500 nodes.  It does less work than the main one would, but it has 
an upper bound on solution value.

**Comment by jjhforrest** [comment]
Looks as if it is complicated.  There may be a better way of fixing but 
the following is safe/simple and should not make any real difference to 
speed.

Changing line 4535 of 2.10.8 CbcModel.cpp to use continuousSolver_ not 
saveSolver should fix

diff --git a/Cbc/src/CbcModel.cpp b/Cbc/src/CbcModel.cpp
@@ -4532,7 +4532,9 @@ void CbcModel::branchAndBound(int doStatistics)
  #endif
          if (tryNewSearch) {
            // back to solver without cuts?
-          OsiSolverInterface *solver2 = saveSolver->clone();
+         // Yes as otherwise not totally safe
+          // OsiSolverInterface *solver2 = saveSolver->clone();
+          OsiSolverInterface *solver2 = continuousSolver_->clone();
            const double *lower = saveSolver->getColLower();

The code tries to use the valid cuts at root as part of the 
preprocessing to get a smaller problem to do a restart.  Afterwards it 
tries to change some of those back into cuts not constraints.  However I 
am not sure that is safe.  The cuts could be flagged as to be applied at 
a solution to see if cuts off, but that may be too complicated.

**Comment by natebragg** [comment]
I don't understand, are you suggesting I just patch my own version of CBC, or that this is the commit you intend to make to fix this?

**Comment by jjhforrest** [comment]
I have updated latest stable - but you may wish to stay with 2.10.8 - in which case just do that patch.

**Comment by natebragg** [comment]
Super!  Thank you.

**Comment by tkralphs** [comment]
I'll make a new release then, in the near future.
