### ISSUE TITLE
Stopping Cbc resolution process

### ISSUE THREAD

**Issue by legraina** [coin-or/Cbc#547]
Hi,

Is there a way to stop CBC resolution process with a callback please ?
I've also tried to use OsiPrimalObjectiveLimit/OsiDualObjectiveLimit, but none seems to work.
Thanks

**Comment by jjhforrest** [comment]
model_->setMaximumNodes(0); should work

**Comment by legraina** [comment]
Thanks. However, I don't think it will fix my issue. It will just stop the resolution at the root node ?
I should have given more context, sorry.
I'm solving a minimization problem, and I'd like to stop the resolution process as soon as I have an integer solution below a certain upper bound that doesn't need to be close to the linear relaxation.

**Comment by jjhforrest** [comment]
Setting to 0 will work.  The code checks number of nodes against maximum at each node and stops if >=. - it is not stop exatly at n nodes.
However what you want could involve one of the parameters allowablegap or ratiogap - which would not need a callback.  If you want something a bit more complicated, you could set the parameter using afterRootCuts event.

**Comment by jhmgoossens** [comment]
If you want full control over what to do when an integer solution is found, then consider the event handler as used in [driver6 example](https://github.com/coin-or/Cbc/blob/df5b8e0f3bc63bfc3cfea0638c6ffc591f7c2acc/examples/driver6.cpp#L198) near line 198. Does that answer your question?

**Comment by legraina** [comment]
@jhmgoossens Thanks, it works perfectly.

Here, my code if it can help someone in the future:
```cpp

#include "CbcEventHandler.hpp" 

class SolCallback : public CbcEventHandler {
 public:
  explicit SolCallback(double ub, CbcModel *model = nullptr):
  CbcEventHandler(model), ub_(ub) {}

  CbcAction event(CbcEvent whichEvent) override {
    if (!model_->parentModel()) {
      if (whichEvent == solution || whichEvent == heuristicSolution) {
        if (model_->getObjValue() <= ub_)
          return stop;  // say finished
      }
    }
    double lb = model_->getBestPossibleObjValue();
    if (lb >= ub)
      return stop;  // say finished
    return noAction;  // carry on
  }

  CbcEventHandler *clone() const override {
    return new SolCallback(ub_, model_);
  }

 private:
  const double ub_;
};
```

Then to add the event handler:
```cpp
std::shared_ptr<SolCallback> pCall = std::make_shared<SolCallback>(ub);
cbcModel->passInEventHandler(pCall.get());
```
