### ISSUE TITLE
problem building the fast0507 example

### ISSUE THREAD

**Issue by amitainz** [coin-or/Cbc#555]
### Discussed in https://github.com/coin-or/Cbc/discussions/554

<div type='discussions-op-text'>

<sup>Originally posted by **amitainz** October 19, 2022</sup>
Hi!

I want to run the fast0507 example.
Running `make DRIVER=fast0507` in the `./Cbc/examples` directory gives the following errors:

```
g++  -O2 -DNDEBUG  -DSAMPLEDIR=\"`echo /via/via_cbc/dist/share/coin-or-sample`\" -DMIPLIB3DIR=\"`echo /via/via_cbc/dist/share/coin-or-miplib3`\" -o fast0507 fast0507.o `PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/via/via_cbc/dist/lib/pkgconfig pkg-config --libs osi-cbc cbc cgl osi-clp`
Undefined symbols for architecture arm64:
  "CbcSolver3::initialize(CbcModel*, char const*)", referenced from:
      _main in fast0507.o
  "CbcSolver3::initialSolve()", referenced from:
      _main in fast0507.o
  "CbcSolver3::CbcSolver3()", referenced from:
      _main in fast0507.o
  "CbcSolver3::~CbcSolver3()", referenced from:
      _main in fast0507.o
  "CbcCompareUser::CbcCompareUser()", referenced from:
      _main in fast0507.o
  "CbcCompareUser::~CbcCompareUser()", referenced from:
      _main in fast0507.o
  "CoinMessageHandler::setLogLevel(int)", referenced from:
      _main in fast0507.o
  "CbcBranchUserDecision::CbcBranchUserDecision()", referenced from:
      _main in fast0507.o
  "CbcBranchUserDecision::~CbcBranchUserDecision()", referenced from:
      _main in fast0507.o
  "typeinfo for CbcSolver3", referenced from:
      _main in fast0507.o
  "typeinfo for OsiSolverInterface", referenced from:
      _main in fast0507.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [fast0507] Error 1
```

Building other targets (e.g. "driver" or "minimum") works ok. I see the files CbcSolver3.hpp and .cpp, but no .o so they clearly haven't been built. I'm a novice to working with Makefile's so if someone can walk me through what needs to be done that'd be great

Thanks,
A.</div>

**Comment by svigerske** [comment]
Some additional files were not compiled and linked. Should be fixed on master now.

To compile, you will need to update Clp as well (to get coin-or/Clp@c4e8ea8031f).

**Comment by amitainz** [comment]
Thanks @svigerske for looking into this.
I ran:
```
./coinbrew fetch Cbc@master
./coinbrew fetch Clp@master
./coinbrew build Cbc@master
./coinbrew build Clp@master
```
all seemed to finish ok (the fetch did rebase on the clp up to the above revision number)
but still:
```
➜  examples git:(master) ✗ make DRIVER=fast0507
g++  -O2 -DNDEBUG  -DSAMPLEDIR=\"`echo /via/via_cbc/dist/share/coin-or-sample`\" -DMIPLIB3DIR=\"`echo /via/via_cbc/dist/share/coin-or-miplib3`\" -o fast0507 fast0507.o `PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/via/via_cbc/dist/lib/pkgconfig pkg-config --libs osi-cbc cbc cgl osi-clp`
Undefined symbols for architecture arm64:
  "CbcSolver3::initialize(CbcModel*, char const*)", referenced from:
      _main in fast0507.o
  "CbcSolver3::initialSolve()", referenced from:
      _main in fast0507.o
  "CbcSolver3::CbcSolver3()", referenced from:
      _main in fast0507.o
  "CbcSolver3::~CbcSolver3()", referenced from:
      _main in fast0507.o
  "CbcCompareUser::CbcCompareUser()", referenced from:
      _main in fast0507.o
  "CbcCompareUser::~CbcCompareUser()", referenced from:
      _main in fast0507.o
  "CoinMessageHandler::setLogLevel(int)", referenced from:
      _main in fast0507.o
  "CbcBranchUserDecision::CbcBranchUserDecision()", referenced from:
      _main in fast0507.o
  "CbcBranchUserDecision::~CbcBranchUserDecision()", referenced from:
      _main in fast0507.o
  "typeinfo for CbcSolver3", referenced from:
      _main in fast0507.o
  "typeinfo for OsiSolverInterface", referenced from:
      _main in fast0507.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [fast0507] Error 1
```
and, fwiw, `make DRIVER=fast0507b` has similar issues with CbcSolver2 instead of CbcSolver3.

**Comment by svigerske** [comment]
Somehow you didn't get the updates in the `Makefile` of examples.
Try running `./config.status` in the directory one up from `examples`.
If that doesn't work, wipe everything that `coinbrew` created and start from scratch.

**Comment by amitainz** [comment]
right, I was just about to post that I didn't run `./configure`. Now that I did, the issue is a lot cleaner:
```
➜  examples git:(master) ✗ make DRIVER=fast0507
g++ -O2 -DNDEBUG  `PKG_CONFIG_PATH=/usr/local/lib/pkgconfig: pkg-config --cflags cbc`  -c -o CbcCompareUser.o `test -f 'CbcCompareUser.cpp' || echo './'`CbcCompareUser.cpp
In file included from CbcCompareUser.cpp:12:
/usr/local/include/coin-or/CbcModel.hpp:3423:13: error: no member named 'setPreProcessingMode' in 'OsiClpSolverInterface'
    osiclp->setPreProcessingMode(processMode);
    ~~~~~~  ^
1 error generated.
make: *** [CbcCompareUser.o] Error 1
```
any ideas how to fix this? Thanks...

**Comment by svigerske** [comment]
Probably some version mismatch.
The examples build against installations of Clp/Cbc, but maybe you didn't install them? Probably `coinbrew install Cbc@master`.

**Comment by amitainz** [comment]
tried pulling the latest (I see commit `8f40aadb0ee6a3a5f56e4585691c69fdcbb3221a`, I guess the above referenced commit was to a different repo? I see the required changes in the makefile at any rate). But now even `minimum` doesn't build:

```
➜  examples git:(master) ✗ make DRIVER=minimum
g++ -O2 -DNDEBUG  `PKG_CONFIG_PATH=/usr/local/lib/pkgconfig: pkg-config --cflags cbc`  -c -o minimum.o `test -f 'minimum.cpp' || echo './'`minimum.cpp
In file included from minimum.cpp:5:
/usr/local/include/coin-or/CbcModel.hpp:3423:13: error: no member named 'setPreProcessingMode' in 'OsiClpSolverInterface'
    osiclp->setPreProcessingMode(processMode);
    ~~~~~~  ^
1 error generated.
make: *** [minimum.o] Error 1
```

**Comment by svigerske** [comment]
As said, make sure you have installed Cbc before trying to build the examples.
If you have some old Cbc (incl Clp) installed in `/usr/local/lib`, then there is a good chance that the examples do not compile with these old headers.

**Comment by amitainz** [comment]
Good point, I see from the output that the wrong PKG_CONFIG_PATH is used. Setting the environment variable outside was not enough, but I just edited the Makefile line myself to read:
```INCL = `PKG_CONFIG_PATH=/path/to/Cbc/dist/lib/pkgconfig pkg-config --cflags cbc` ```
instead of 
```INCL = `PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/path/to/Cbc/dist/lib/pkgconfig ...` ```
and now it seems all the examples build ok, thanks!

**Comment by tkralphs** [comment]
A few `coinbrew` pointers.

- If you want to install everything in `/usr/local`, you can just add `--prefix=/usr/local` to your `coinbrew` build command. 
- You don't need to (and usually shouldn't) separately fetch Clp. Fetching Cbc already automatically fetches the most recent compatible version of Clp.

**Comment by amitainz** [comment]
thanks!
