### ISSUE TITLE
printingOptions bound sometimes results in empty file

### ISSUE THREAD

**Issue by raller09** [coin-or/Cbc#586]
Hi,

I'm testing with cbc + sensetivity information.

[sens_semi.mps.txt](https://github.com/coin-or/Cbc/files/11139632/sens_semi.mps.txt)

With a batch cbc.bat
`@echo off
cbc.exe %1 directory %~dp0 solve printingOptions all solution %~n1.all.txt printingOptions objective solution %~n1.objective.txt printingOptions rhs solution %~n1.rhs.txt printingOptions bound solution %~n1.bound.txt
Echo %errorlevel%`

cbc.bat sens_semi.mps

I receive sometimes/mostly an empty "sens_semi.mps.bound.txt" file.
sometimes I receive bounds...

I haven't been able to pinpoint a reason or difference yet.

With the stin interface
`cbc.exe sens_semi.mps -
solve
printingOptions bound`

on one test one name was a "Black Club Suit"?!?

`D:\Temp\lpsolver\Cbc-releases.2.10.8-w64-msvc17-md\bin>cbc.exe sens_semi.mps -
Welcome to the CBC MILP Solver
Version: 2.10.8
Build Date: May  5 2022

command line - cbc.exe sens_semi.mps - (default strategy 1)
At line 11 NAME          L
At line 12 ROWS
At line 17 COLUMNS
At line 25 RHS
At line 28 BOUNDS
At line 32 ENDATA
Problem L has 3 rows, 4 columns and 7 elements
1 semi-continuous variables - report odd behavior
Coin0008I L read with 0 errors
Switching to line mode
Coin:solve
Continuous objective value is 31.7828 - 0.00 seconds
No integer variables - nothing to do
Cgl0004I processed model has 3 rows, 4 columns (0 integer (0 of which binary)) and 7 elements
Cbc3007W No integer variables - nothing to do
Cbc0036I Heuristics switched off as 1 branching objects are of wrong type
Cbc0004I Integer solution of 31.782759 found after 0 iterations and 0 nodes (0.00 seconds)
Cbc0001I Search completed - best objective 31.78275862068966, took 0 iterations and 0 nodes (0.00 seconds)
Cbc0035I Maximum depth 0, 0 variables fixed on reduced cost
Cuts at root node changed objective from 31.7828 to 31.7828
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
3 bounds tightened after postprocessing

Result - Optimal solution found

Objective value:                31.78275862
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.01

Coin:printingOptions bound
Option for printingOptions changed from normal to bound!ranging
Coin:solution$
No match for solution$ - ? for list of commands
Coin:solution $
Bound ranging,name,increase,variable,decrease,variable
Optimal - objective value 31.782759
Optimal - objective value 31.782759
0,COLONE,33.06666667,THATROW,30.54359839,LASTROW
1,COLTWO,0.5123945822,COLFOUR,0.6355992844,COLFOUR
2,COLTHREE,0.7016799293,THATROW,4841.160345,LASTROW
3,COLFOUR,31.82758621,♣,18,THATROW
Coin:quit
Total time (CPU seconds):       170.72   (Wallclock seconds):       170.72`

Do I somthing worg or is this a problem with cbc?

**Comment by raller09** [comment]
Hi,

I tested some more:

Im starting cbc.exe with Windows CreateProcess with a StdOutput handle/file.

Sometimes the "printingOptions bound" file correct. After a second start of cbc the file is empty or the last added entry ist cut off (somewhere in the middle). If it happens, then with the first binary variable.

This also cuts off the result of the log file in the middle. Sometimes the log file is empty.
I assume there is a program crash taking place here.

If these problems occur, then the execution takes much longer.  100 milli seconds to 2-5 seconds

[empty_bound_file.zip](https://github.com/coin-or/Cbc/files/11149836/empty_bound_file.zip)

But why does the first run results to a correct file?

I think this is an access error/overflow?
I don't think I can find/solve this myself.

Thank you

**Comment by raller09** [comment]
Hi,

i compiled + tested master branch with VS 2022and the following command line:

`"D:\git\coin-or\coinbrew\Cbc\MSVisualStudio\v17\x64\Debug\lpiAFF8.mps -solve -printingOptions bound -solution xxx.bound.txt"`

+ get a access violation:

```
---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Debug Assertion Failed!

Program: D:\git\coin-or\coinbrew\Cbc\MSVisualStudio\v17\x64\Debug\cbc.exe
File: C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.35.32215\include\vector
Line: 1949

Expression: vector subscript out of range
```

does the following change need to be made?

```
D:\git\coin-or\coinbrew\Cbc\src\CbcSolver.cpp, Line 10959:

                    solver->primalRanging(number, which, valueIncrease,
                                          sequenceIncrease, valueDecrease,
                                          sequenceDecrease);
```
                                          
change "numberRows" -> "number"
arrays created with "...[number]"
with 
"int number = numberColumns;"

D:\git\coin-or\coinbrew\Clp\src\ClpSimplexOther.cpp
line 760 - primalRanging -> comment "0..numberColumns"

Thank you

**Comment by jjhforrest** [comment]
Thanks for finding this bug.  I have made change (also in stable - although there it does not crash - but gives wrong result)
