### ISSUE TITLE
Trouble creating vcpkg port

### ISSUE THREAD

**Issue by jpfeuffer** [coin-or/Cbc#602]
Sorry that I have to forward this here but I have never used autoconf except for when it JustWorks.

Maybe you guys have some insights on what is wrong. If you look at the build script in my PR I THINK I am using the contents of the build tools repository as mentioned often around the internet.

e.g. on Windows x64:
```
autoreconf: export WARNINGS=
autoreconf: Entering directory '.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I "D:/buildtrees/coin-or-cbc/src/8ad995b231-cec7df5550.clean/BuildTools" --force 
am-wrapper: aclocal: warning: auto-detected versions not found (1.9); falling back to latest available
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: configure.ac: not using Intltool
autoreconf: configure.ac: not using Gtkdoc
autoreconf: running: /usr/bin/autoconf --force
configure.ac:39: error: possibly undefined macro: AC_COIN_CREATE_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:45: error: possibly undefined macro: AC_COIN_MAIN_PACKAGEDIR
autoreconf: error: /usr/bin/autoconf failed with exit status: 1
```

or macOS pretty much the same:

```
autoreconf: export WARNINGS=
autoreconf: Entering directory '.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I "/Users/vagrant/Data/buildtrees/coin-or-cbc/src/8ad995b231-cec7df5550.clean/BuildTools" --force 
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: configure.ac: not using Intltool
autoreconf: configure.ac: not using Gtkdoc
autoreconf: running: /usr/local/Cellar/autoconf/2.71/bin/autoconf --force
configure.ac:39: error: possibly undefined macro: AC_COIN_CREATE_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:45: error: possibly undefined macro: AC_COIN_MAIN_PACKAGEDIR
autoreconf: error: /usr/local/Cellar/autoconf/2.71/bin/autoconf failed with exit status: 1
```

_Originally posted by @jpfeuffer in https://github.com/microsoft/vcpkg/pull/31607#issuecomment-1561263781_

**Comment by svigerske** [comment]
Don't attempt to autoreconf. https://github.com/microsoft/vcpkg/pull/31607#issuecomment-1561759300 is correct.

For current Cbc releases, you'll have to live with the configure script that is generated by a very old autotools.
Branch master has been updated for use with very recent autotools years ago, but no release from that branch is in sight.

**Comment by jpfeuffer** [comment]
So if I chose to build from a specific point on master, it should work?
Which version of buildtools do I need to use then? Latest (0.8) or also master?

**Comment by jpfeuffer** [comment]
I am just wondering how the rest of the coinor packages work flawlessly on vcpkg.
I noticed that they are not using release versions  but dates, so they might be builds from master.

**Comment by svigerske** [comment]
You can try with the current master and try to avoid running autotools (autoreconf, etc). But if you have to, then use current master of BuildTools. That applies additional patches for builds with MS/Intel compilers on Windows.

I have no experience with vcpkg.

**Comment by jpfeuffer** [comment]
Ok thank you very much! Last (newbie) question: what is the alternative to autotools for cbc? What should I run instead?

**Comment by svigerske** [comment]
Running the usual configure/make/make-install is preferred, in my opinion. What I meant was that it is best to avoid recreating configure, etc, by running autoreconf. Just use the configure that is distributed.

**Comment by jpfeuffer** [comment]
Hi!
I now managed to build it on all platforms but Windows which seems to have problems with pkgconfig and its paths.
See https://github.com/microsoft/vcpkg/pull/31607#issuecomment-1565376051

Do you have any idea how to solve that?
