### ISSUE TITLE
Marginal vlaues/Shadow prices form CCB outputs

### ISSUE THREAD

**Issue by vignesh1987** [coin-or/Cbc#609]
Hi, 

I would like to view the marginal values for an optimisation problem that I work on. When I use other solvers like Glpsol or CPLEX, or Gurobi, it is simpler to spit out the dual/marginal values. However, when I use CBC as the solver, it gives out a compact solutions file but not the marginal values. Can someone guide me on obtaining the marginal values while working with CBC? I use the following command to write the CBC solutions file. data_file.lp is the LP file that I generate using GLPK and results.txt is my results file.
```
cbc data_file.lp solve -solu results.txt
```

**Comment by jjhforrest** [comment]
Default printing does give reduced costs - but only for non-zero variables.

Add -printing all to get duals and reduced costs for all variables

**Comment by vignesh1987** [comment]
Thanks @jjhforrest . "-printing all" get the duals at the end for each constraint in the model.
