### ISSUE TITLE
CBC fails when initial solution is passed with mipstart

### ISSUE THREAD

**Issue by asortino** [coin-or/Cbc#627]
Hello,
I'm running into an issue with CBC 2.10.11 when providing a MIP start solution. When I run

`cbc -import /tmp/tmp4rm8vens.pyomo.lp -mipstart /tmp/tmp_dba7oe5.cbc.soln -solve`

the solver fails without a clear message:

```
Welcome to the CBC MILP Solver 
Version: 2.10.11 
Build Date: Oct 26 2023 

command line - cbc -import /tmp/tmp4rm8vens.pyomo.lp -mipstart /tmp/tmp_dba7oe5.cbc.soln -solve (default strategy 1)
opening mipstart file /tmp/tmp_dba7oe5.cbc.soln.
MIPStart values read for 224 variables.
Continuous objective value is 1.30606 - 0.11 seconds
Cgl0008I 595 inequality constraints converted to equality constraints
Cgl0003I 1256 fixed, 0 tightened bounds, 6540 strengthened rows, 8 substitutions
Cgl0003I 0 fixed, 0 tightened bounds, 561 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 0 tightened bounds, 4510 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 0 tightened bounds, 2630 strengthened rows, 0 substitutions
Cgl0003I 1 fixed, 0 tightened bounds, 2375 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 0 tightened bounds, 1 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 0 tightened bounds, 825 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 0 tightened bounds, 577 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 0 tightened bounds, 140 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 0 tightened bounds, 28 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 0 tightened bounds, 2 strengthened rows, 0 substitutions
Cgl0004I processed model has 8771 rows, 3824 columns (3179 integer (3179 of which binary)) and 55309 elements
Illegal index 4536 in ClpModel::getColumnName
terminate called after throwing an instance of 'CoinError'
[1]    15666 IOT instruction (core dumped)  cbc -import /tmp/tmp4rm8vens.pyomo.lp -mipstart /tmp/tmp_dba7oe5.cbc.soln
```

Attached both the problem definition and the initial solution.
[tmp4rm8vens.pyomo.lp.txt](https://github.com/coin-or/Cbc/files/13440738/tmp4rm8vens.pyomo.lp.txt)
[tmp_dba7oe5.cbc.soln.txt](https://github.com/coin-or/Cbc/files/13440739/tmp_dba7oe5.cbc.soln.txt)

If no solution is provided the solver works fine.

**Comment by jjhforrest** [comment]
It works with master.  I have updated stable with what was modified there

-- a/Cbc/src/CbcSolver.cpp
+++ b/Cbc/src/CbcSolver.cpp
@@ -5808,7 +5808,7 @@ int CbcMain1(int argc, const char *argv[],
                     std::vector< std::pair< std::string, double > > mipStart2;
                     for (int i = 0; (i < babModel_->solver()->getNumCols()); ++i) {
                       int iColumn = babModel_->originalColumns()[i];
-                      if (iColumn >= 0) {
+                      if (iColumn >= 0 && iColumn < model.getNumCols()) {
                         std::string cname = model_.solver()->getColName(iColumn);
                         colNames.push_back(cname);
                         babModel_->solver()->setColName(i, cname);
jo

**Comment by asortino** [comment]
Thank you!

**Comment by asortino** [comment]
Thank you very much! It works for me too. Probably the version installed using `sudo pacman -S coin-or-cbc` is broken.
Closing the issue.
