### ISSUE TITLE
Error installing Cbc solver in a docker image

### ISSUE THREAD

**Issue by Abdullah13521** [coin-or/Cbc#634]
I'm getting this error when installing the Cbc solver in docker: `cannot guess build type; you must specify one`

Here is my code: 
```
# Download repository with CBC solver and intstall
RUN git clone https://github.com/coin-or/coinbrew /var/cbc
WORKDIR /var/cbc
RUN ./coinbrew fetch Cbc --no-prompt --no-third-party
RUN ./coinbrew build Cbc --no-prompt --no-third-party --prefix=/usr
ENV COIN_INSTALL_DIR /usr
```

Any idea how to fix it?

**Comment by svigerske** [comment]
Specifying a build type could work (https://www.gnu.org/software/autoconf/manual/autoconf-2.68/html_node/System-Type.html). What is the Docker base image (OS and CPU architecture) here?

**Comment by Abdullah13521** [comment]
thanks for the link. It worked after adding this:
`RUN ./coinbrew build Cbc --no-prompt --no-third-party --prefix=/usr --build=x86_64-linux`
