### ISSUE TITLE
osiUnitTest failure

### ISSUE THREAD

**Issue by pgrt** [coin-or/Cbc#635]
Dear Developers,

I am the Debian maintainer of Cbc. I noticed, with Cbc/2.10.11 (but not only), that the invocation
`./osiUnitTest -mpsDir=/usr/share/coin/Data/Sample`
in the unit tests (look for "mpsDir" in the log https://buildd.debian.org/status/fetch.php?pkg=coinor-cbc&arch=amd64&ver=2.10.11%2Bds1-1%2Bb1&stamp=1704488536&raw=0) silently fails with

Coin0008I EXAMPLE read with 0 errors
Illegal index 0 in OsiClpSolverInterface::setObjCoeff
Coin0008I EXAMPLE read with 0 errors
Illegal index 20 in OsiClpSolverInterface::setColSetBounds

which are raised by assertions in Clp/src/ClpSimplex.cpp if built against Clp (e.g. its version 1.17.9) and Clp has assertions enabled. Without the assertions osiUnitTest fails loudly with a segmentation fault.

I would be happy to provide more indications if I can,

Best,

Pierre

**Comment by jjhforrest** [comment]
Those illegal index messages are meant to happen.  That code is normally only entered if NDEBUG is not set.  If parts of code are compiled with NDEBUG and parts without you will get seg faults.

**Comment by pgrt** [comment]
So that's odd from me, I was just being inconsistent with NDEBUG... thanks a lot for your help, and sorry for the noise.

Best wishes,

Pierre
