### ISSUE TITLE
example where cbc does not find global optimum

### ISSUE THREAD

**Issue by svigerske** [coin-or/Cbc#89]
Issue created by migration from Trac.

Original creator: janpoland

Original creation time: 2010-04-16 14:32:04

Assignee: somebody

Version: 2.0

Keywords: global optimum

In the following example, I get a feasible solution with cbc (the command line version cbcSolver) which is suboptimal. If I use the minimum.cpp call instead, cbc does find the optimum, however takes significantly longer time.

The example consists of the following files:
(1) example.mps : the problem definition
(2) example_cbc_found1.txt : the solution found by cbc
(3) example_cbc_found.txt : again the same solution in a different format (sparse matrix format where line 1 contains numrows numcols 0, and each further line contains i j A[i,j])
(4) example_optimum.txt : the optimum in sparse matrix format
(5) otherexample.mps : a very similar (even slightly larger) example where cbc does find the global optimum

I get the problem with different versions of cbc, e.g. 2.3.2. and 2.4.1.
Many thanks for looking into this!
Jan.

**Comment by svigerske** [comment]
Attachment [cbc_suboptimal.zip](https://www.coin-or.org/issue-attachments/Cbc/ticket89/cbc_suboptimal.zip) by janpoland created at 2010-04-16 14:32:25

**Comment by svigerske** [comment]
Comment by @tkralphs created at 2010-04-16 21:01:03

Changing assignee from somebody to @tkralphs.

**Comment by svigerske** [comment]
Comment by @tkralphs created at 2010-04-16 21:01:03

Changing status from new to assigned.

**Comment by svigerske** [comment]
Comment by @tkralphs created at 2010-04-16 21:01:03

Version changed from 2.0 to 2.4.1

**Comment by svigerske** [comment]
@jjhforrest This one still seems to have an issue. If I run example.mps or otherexample.mps from the attached zip with current Cbc/master, I get
```
Welcome to the CBC MILP Solver 
Version: Trunk (unstable) 
Build Date: Mar 12 2019 
Revision Number: 2526 

command line - ./bin/cbc example.mps (default strategy 1)
At line 1 NAME          BLANK
At line 2 ROWS
At line 1119 COLUMNS
At line 2991 RHS
At line 3281 RANGES
At line 3287 BOUNDS
At line 3694 ENDATA
Problem BLANK has 1115 rows, 545 columns and 3218 elements
Coin0008I BLANK read with 0 errors
Continuous objective value is 426.409 - 0.02 seconds
Cgl0000I Cut generators found to be infeasible! (or unbounded)
Pre-processing says infeasible or unbounded
Total time (CPU seconds):       0.12   (Wallclock seconds):       0.13

command line - ./bin/cbc otherexample.mps (default strategy 1)
At line 1 NAME          BLANK
At line 2 ROWS
At line 1245 COLUMNS
At line 3329 RHS
At line 3651 RANGES
At line 3657 BOUNDS
At line 4109 ENDATA
Problem BLANK has 1241 rows, 606 columns and 3584 elements
Coin0008I BLANK read with 0 errors
Continuous objective value is 444.325 - 0.02 seconds
Cgl0000I Cut generators found to be infeasible! (or unbounded)
Pre-processing says infeasible or unbounded
Total time (CPU seconds):       0.13   (Wallclock seconds):       0.13
```
However, SCIP claims that both are feasible and bounded. There, example.mps has optimal value +6.52890811216114e+02 and otherexample.mps has +7.07521853238278e+02.

Could you have a look what the problem is here?

**Comment by jjhforrest** [comment]
It looks as if it is feasible with tolerance 1.0e-5 - cbc says infeasible with 1.0e6.  Also scaling on/off makes a difference.  Not sure what to do.

**Comment by svigerske** [comment]
Numerics happen. Might be both feasible and infeasible.
